### ISSUE TITLE
Getting an ERROR when I try to play something

### ISSUE THREAD

**Issue by Dhruv-2103** [codetheweb/muse#1009]
🚫 ope: Error: Cannot find module '/home/container/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-glibc-2.31/opus.node'
Require stack:
/home/container/node_modules/@discordjs/opus/lib/index.js
/home/container/node_modules/prism-media/src/util/loader.js
/home/container/node_modules/prism-media/src/opus/Opus.js
/home/container/node_modules/prism-media/src/opus/index.js
/home/container/node_modules/prism-media/src/index.js
Error: Cannot find module 'node-opus'
Require stack:
/home/container/node_modules/prism-media/src/util/loader.js
/home/container/node_modules/prism-media/src/opus/Opus.js
/home/container/node_modules/prism-media/src/opus/index.js
/home/container/node_modules/prism-media/src/index.js
Error: Cannot find module 'opusscript'
Require stack:
/home/container/node_modules/prism-media/src/util/loader.js
/home/container/node_modules/prism-media/src/opus/Opus.js
/home/container/node_modules/prism-media/src/opus/index.js
/home/container/node_modules/prism-media/src/index.js

This is my console
v16.20.2
:/home/container$ npm start

> muse@2.7.1 start
> npm run env:set-database-url -- tsx src/scripts/migrate-and-start.ts

> muse@2.7.1 env:set-database-url
> tsx src/scripts/run-with-database-url.ts tsx src/scripts/migrate-and-start.ts

========================================
========================================
================= muse =================
========================================
=========== Made with 🎶 by ============
==== https://github.com/codetheweb =====
========================================
========================================

Running version 2.7.1 built on unknown date (commit unknown)

🔧 Need help? https://github.com/codetheweb/muse/discussions/new
🐛 Bug? https://github.com/codetheweb/muse/issues/new
✨ New feature? https://github.com/codetheweb/muse/issues/new
☕ Discussion? https://github.com/codetheweb/muse/discussions/new
💰 Help me? https://www.paypal.me/codetheweb https://github.com/sponsors/codetheweb

✔ Database migrations applied.
✔ Ready! Invite the bot with https://discordapp.com/oauth2/authorize?client_id=1181969762159439983&scope=bot%20applications.commands&permissions=36700160

**Comment by wcdfilll** [comment]
me too

**Comment by codetheweb** [comment]
It would be helpful if you provided more details about your system. Are you running in Docker or from the cloned repository?

**Comment by wcdfilll** [comment]
> It would be helpful if you provided more details about your system. Are you running in Docker or from the cloned repository?

i was fixed, sorry, im running it on Pterodactyl, so it is like that, thank you
