### ISSUE TITLE
2.8.1 not the latest on dockerhub

### ISSUE THREAD

**Issue by Maikel1990** [codetheweb/muse#1027]
Hi,

I usually use  the latest image and auto update it when there is a new one. I noticed the bot was gone offline and after searching there was a patch in 2.8.1 but this is not the latest on docker hub so i'm forced to use the 2.8.1 image now.

**Comment by Bennylavaa** [comment]
This was updated 3 days ago https://hub.docker.com/r/codetheweb/muse
