### ISSUE TITLE
Command: "/config set-queue-add-response-hidden" fails with error: "ope: unknown subcommand"

### ISSUE THREAD

**Issue by valkyrgit** [codetheweb/muse#1029]
**What's happening?**
Concisely describe what's going wrong.

When attempting to run the command "/config set-queue-add-response-hidden" it returns the "unknown subcommand" error with both the "true" and "false" value options. 

**Logs**

```
2024-05-03T16:05:30.423Z prisma:client  Prisma Client call:
2024-05-03T16:05:30.423Z prisma:client  prisma.setting.findUnique({
  where: {
    guildId: '581974284428247041'
  }
})
2024-05-03T16:05:30.423Z prisma:client  Generated request:
2024-05-03T16:05:30.423Z prisma:client  query {
  findUniqueSetting(where: {
    guildId: "581974284428247041"
  }) {
    guildId
    playlistLimit
    secondsToWaitAfterQueueEmpties
    leaveIfNoListeners
    queueAddResponseEphemeral
    autoAnnounceNextSong
    defaultVolume
    createdAt
    updatedAt
  }
}

2024-05-03T16:05:30.423Z prisma:client:libraryEngine  sending request, this.libraryStarted: true
2024-05-03T16:05:30.425Z muse /usr/app/src/commands/config.ts:203
        throw new Error('unknown subcommand');
              ^

Error: unknown subcommand
    at default_1.execute (/usr/app/src/commands/config.ts:203:15)
    at Client.<anonymous> (/usr/app/src/bot.ts:79:13)
```

**Runtime**
I'm running Muse:
- [ ] Directly from the cloned repository
- [X ] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: 2.8.1
- Docker (if applicable): Docker version 24.0.9, build 2936816
- OS: unRAID
- Node.js: (if running outside the Docker container)
- ffmpeg: (if running outside the Docker container, 4.1 or later is required)

**Comment by gknoop** [comment]
> **What's happening?** Concisely describe what's going wrong.
> 
> When attempting to run the command "/config set-queue-add-response-hidden" it returns the "unknown subcommand" error with both the "true" and "false" value options.
> 
> **Logs**
> 
> ```
> 2024-05-03T16:05:30.423Z prisma:client  Prisma Client call:
> 2024-05-03T16:05:30.423Z prisma:client  prisma.setting.findUnique({
>   where: {
>     guildId: '581974284428247041'
>   }
> })
> 2024-05-03T16:05:30.423Z prisma:client  Generated request:
> 2024-05-03T16:05:30.423Z prisma:client  query {
>   findUniqueSetting(where: {
>     guildId: "581974284428247041"
>   }) {
>     guildId
>     playlistLimit
>     secondsToWaitAfterQueueEmpties
>     leaveIfNoListeners
>     queueAddResponseEphemeral
>     autoAnnounceNextSong
>     defaultVolume
>     createdAt
>     updatedAt
>   }
> }
> 
> 2024-05-03T16:05:30.423Z prisma:client:libraryEngine  sending request, this.libraryStarted: true
> 2024-05-03T16:05:30.425Z muse /usr/app/src/commands/config.ts:203
>         throw new Error('unknown subcommand');
>               ^
> 
> Error: unknown subcommand
>     at default_1.execute (/usr/app/src/commands/config.ts:203:15)
>     at Client.<anonymous> (/usr/app/src/bot.ts:79:13)
> ```
> 
> **Runtime** I'm running Muse:
> 
>     * [ ]  Directly from the cloned repository
> 
>     * [X ] Inside a Docker container
> 
>     * [ ]  Something else (please elaborate)
> 
> 
> **Versions**
> 
>     * Muse: 2.8.1
> 
>     * Docker (if applicable): Docker version 24.0.9, build 2936816
> 
>     * OS: unRAID
> 
>     * Node.js: (if running outside the Docker container)
> 
>     * ffmpeg: (if running outside the Docker container, 4.1 or later is required)

You are certainly not alone. Just so you know, several of us have had the same issue.
https://github.com/codetheweb/muse/issues/998#issuecomment-2108875244

**Comment by Sheeley7** [comment]
I created a pull request to fix this, just waiting for it to be approved and merged:
https://github.com/codetheweb/muse/pull/1025#issue-2267992756

if you’re savvy enough, you can edit the SQLite database entry to set the flag manually until the pull request gets approved.
