### ISSUE TITLE
Unable to play any songs

### ISSUE THREAD

**Issue by MintyFreshers** [codetheweb/muse#1037]
**What's happening?**
I am currently getting an error when trying to play any songs, the bot says "ope: No playing song found".

**Logs**

```
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: true +6ms
  prisma:client  Prisma Client call: +6ms
  prisma:client  prisma.fileCache.findUnique({
  where: {
    hash: 'afd225007a8561b11ff551d42cd062fead6b66e44d920fc0b2f6a45c37871fce1b7539264a0409f3076aa27ecffb54de11d2466a86c939714632e50c9d55c7ae'
  }
}) +0ms
  prisma:client  Generated request: +0ms
  prisma:client  query {
  findUniqueFileCache(where: {
    hash: "afd225007a8561b11ff551d42cd062fead6b66e44d920fc0b2f6a45c37871fce1b7539264a0409f3076aa27ecffb54de11d2466a86c939714632e50c9d55c7ae"
  }) {
    hash
    bytes
    accessedAt
    createdAt
    updatedAt
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: true +6ms
  muse [VOICE] received voice state update: {"member":{"user":{"username":"SwoftBot","public_flags":0,"id":"985127745015128084","global_name":null,"display_name":null,"discriminator":"3140","clan":null,"bot":true,"avatar_decoration_data":null,"avatar":"9eb046c7d270f2fa7e83394af0e2b30c"},"roles":["987505496963555339"],"premium_since":null,"pending":false,"nick":null,"mute":false,"joined_at":"2022-06-17T23:54:17.468000+00:00","flags":0,"deaf":false,"communication_disabled_until":null,"avatar":null},"user_id":"985127745015128084","suppress":false,"session_id":"b8c909325b5757be574d3d2486b4988a","self_video":false,"self_mute":false,"self_deaf":true,"request_to_speak_timestamp":null,"mute":false,"guild_id":"136921565056073728","deaf":false,"channel_id":"505091962995474446"} +109ms
  prisma:client  Prisma Client call: +101ms
  prisma:client  prisma.setting.findUnique({
  where: {
    guildId: '136921565056073728'
  }
}) +1ms
  prisma:client  Generated request: +0ms
  prisma:client  query {
  findUniqueSetting(where: {
    guildId: "136921565056073728"
  }) {
    guildId
    playlistLimit
    secondsToWaitAfterQueueEmpties
    leaveIfNoListeners
    queueAddResponseEphemeral
    autoAnnounceNextSong
    defaultVolume
    createdAt
    updatedAt
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: true +103ms
  muse [VOICE] received voice server: {"t":"VOICE_SERVER_UPDATE","s":8,"op":0,"d":{"token":"621e7999a1fccdaa","guild_id":"136921565056073728","endpoint":"us-east7654.discord.media:443"}} +25ms
  prisma:client  Prisma Client call: +1s
  prisma:client  prisma.setting.findUnique({
  where: {
    guildId: '136921565056073728'
  }
}) +0ms
  prisma:client  Generated request: +1ms
  prisma:client  query {
  findUniqueSetting(where: {
    guildId: "136921565056073728"
  }) {
    guildId
    playlistLimit
    secondsToWaitAfterQueueEmpties
    leaveIfNoListeners
    queueAddResponseEphemeral
    autoAnnounceNextSong
    defaultVolume
    createdAt
    updatedAt
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: true +1s
  muse Rick Astley - Never Gonna Give You Up (Official Music Video) is unavailable +1s
  muse Error: No playing song found
  muse     at buildPlayingMessageEmbed (file:///opt/bot/src/utils/build-embed.ts:1:1533)
  muse     at AddQueryToQueue.addToQueue (file:///opt/bot/src/services/add-query-to-queue.ts:1:3628)
  muse     at async play_default.execute (file:///opt/bot/src/commands/play.ts:1:1604)
  muse     at async Client.<anonymous> (file:///opt/bot/src/bot.ts:1:2354) +1ms

```

**Screenshots**
![image](https://github.com/codetheweb/muse/assets/8878961/b44b5d3e-db44-49ad-836b-a53edf07cd10)

**Runtime**
I'm running Muse:
- [x] Directly from the cloned repository
- [ ] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: v2.8.1
- Docker (if applicable): N/A
- OS: Debian GNU/Linux 12
- Node.js: v18.19.0
- ffmpeg: ffmpeg version 5.1.4-0+deb12u1

**Comment by DrNefarius** [comment]
Same thing here, also running in a docker dontainer.
What I found is that some youtube videos actually do play, like Rick Astleys Never gonna give you up, when using the autocomplete feature and selecting the Spotify result:

query: spotify:track:4PTG3Z6ehGkBFwjybzWkR8

Though the youtube query also works for this song:

query: https://www.youtube.com/watch?v=dQw4w9WgXcQ

However for example "Never Gonna Stop" also from Rick Astley, doesn't work and gives the result as stated by the issue:

query: https://www.youtube.com/watch?v=qWNQUvIk954
or
query: spotify:track:7koIUHBD4AZoEP8Wuu9xQf

**Comment by bu3alwa** [comment]
I am getting the same thing and I just started using the project with the dockerized container. The bot comes in muted on spotify as well.

**Comment by im-trisha** [comment]
@bu3alwa Yes I am, however, this is not the problem I think, because in the google cloud console the API requests are successful, so it'd have no sense to be a youtube's problem

**Comment by bu3alwa** [comment]
> @bu3alwa Yes I am, however, this is not the problem I think, because in the google cloud console the API requests are successful, so it'd have no sense to be a youtube's problem

I was ablw to get it to work locally but not on vps. Same docker container. So my assumption is some sort of limiting.

Are you able to try your bot locally and see if it works vs on a vps?

**Comment by MindHardt** [comment]
I also faced this issue when deployed bot to my new VPS. But when I instead deployed it on my local server it worked fine.

**Comment by burntcookie90** [comment]
I have it deployed locally and it's running into this issue

**Comment by bu3alwa** [comment]
Mine started working on vps after I stopped it for a while. For my case I am pretty sure it was throttling from youtubes side on my ip.

**Comment by im-trisha** [comment]
@bu3alwa mine still doesn't work.

**Comment by lone-dancer** [comment]
I'm running into a similar issue (Docker container) where after working just fine, it suddenly stopped working and while you can add songs, they do not play and the queue/now-playing say they are empty

**Comment by xxtensazenxx** [comment]
Same issue here. I was using a docker container and had the bot up and running for over a year - not a single issue. Now this :l

**Comment by im-trisha** [comment]
With a quick glance at the code, it seems that the problem is what it appears to be, the song isn't queue'd:
`typescript
await player.play();

if (wasPlayingSong) {
  statusMsg = 'resuming playback';
}

await interaction.editReply({
  embeds: [buildPlayingMessageEmbed(player)],
});
`
Here, `player.play` runs the function `this.getCurrent()` successfully and finds a song, or else he'd be the one throwing the error (See [here](https://github.com/codetheweb/muse/blob/29b61cc0b6363b3e07f17bd7d41400d20827f959/src/services/player.ts#L192))

But right after, `buildPlayingMessageEmbed` throws "No playing sound found" (See [here](https://github.com/codetheweb/muse/blob/29b61cc0b6363b3e07f17bd7d41400d20827f959/src/utils/build-embed.ts#L58)). 

At least, it seems to be like this. I don't have a chance to try the code myself

This seems like just a logical error, I could be totally wrong thought. @codetheweb I think this isn't an impossible/long fix. Hope I can help with a PR soon

**Comment by zylinx** [comment]
thought id try the bot, this is all im getting from the get go, using docker image with all tokens set. i tried 2.8.1 and latest muse. 
the bot joins the VC, displays the Now Playing but then never plays anything and just disconnects. I cant find any logs.

**Comment by gan11a** [comment]
Same issue, running docker image in Unraid locally. Song adds, but queue is empty.

**Comment by leshicodes** [comment]
+1

**Comment by Wek-mad** [comment]
+1 the bot now won't play anything, I'm running on docker linux

**Comment by german-moreno283** [comment]
+1 also not working on Linux using docker

**Comment by Azmekk** [comment]
+1 from me as well. Running with docker compose in Ubuntu 22.04.4 LTS and it's adding songs but nothing is playing. Logs aren't displaying any errors either.

**Comment by frunkAF** [comment]
I tried deploying the container using a 2.7.1 and it's still not playing.

This may be an issue with the spotify and/or youtube api?

**Comment by EugeneLeclerc** [comment]
Yeah it was a breaking change by Youtube, it broke everything. The easiest solution is to switch to https://github.com/distubejs/ytdl-core, which already released a fix. This is what this PR https://github.com/codetheweb/muse/pull/1042 proposes, but it has not been accepted yet.

In the mean time, if anyone want to fix their own Docker installation, you can add this to your Dockerfile:
```    
# Temporary fix for https://github.com/codetheweb/muse/issues/1037
entrypoint: bash 
command: -c "npm install @distube/ytdl-core@latest && sed -i 's%ytdl-core%@distube/ytdl-core%g' src/services/player.ts && tini -- yarn start"
```

It installs @distube/ytdl-core and replaces imports in the code.

**Comment by frunkAF** [comment]
> Yeah it was a breaking change by Youtube, it broke everything. The easiest solution is to switch to https://github.com/distubejs/ytdl-core, which already released a fix. This is what this PR #1042 proposes, but it has not been accepted yet.
> 
> In the mean time, if anyone want to fix their own Docker installation, you can add this to your Dockerfile:
> 
> ```
> # Temporary fix for https://github.com/codetheweb/muse/issues/1037
> entrypoint: bash 
> command: -c "npm install @distube/ytdl-core@latest && sed -i 's%ytdl-core%@distube/ytdl-core%g' src/services/player.ts && tini -- yarn start"
> ```
> 
> It installs @distube/ytdl-core and replaces imports in the code.

I did the following in my compose file...

services:
  muse:
    container_name: muse
    image: codetheweb/muse:latest
    deploy:
      resources:
        limits:
          cpus: '2'
    user: 423:423
    environment:
      - SPOTIFY_CLIENT_ID=<REDACTED>
      - SPOTIFY_CLIENT_SECRET=<REDACTED>
      - YOUTUBE_API_KEY=<REDACTED>
      - DISCORD_TOKEN=<REDACTED>
    entrypoint: /bin/bash 
    command: -c "npm install @distube/ytdl-core@latest && sed -i 's%ytdl-core%@distube/ytdl-core%g' src/services/player.ts && tini -- yarn start"
    network_mode: bridge
    volumes:
      - /docker/muse-mn:/data:rw
    restart: unless-stopped
    
    the container creates but doesn't seem to be functioning. absolutely no messages in the stdout

**Comment by EugeneLeclerc** [comment]
> I did the following in my compose file...
> 
> the container creates but doesn't seem to be functioning. absolutely no messages in the stdout

No error at all in the container output? Does the node process start correctly?

**Comment by Renaud11232** [comment]
Another workaround while waiting for #1042 to be merged, is to use `codetheweb/muse:pr-1042` or `codetheweb/muse:584bb17b73594b8fcfad6a9aefb2abe3d17f3ce8` instead of `codetheweb/muse:latest`.

Works fine for me.

**Comment by EugeneLeclerc** [comment]
> This is what I get when I try adding it in my compose file:
> 
> ```
> [+] Running 2/2
>  ✔ Network muse_default   Created                                                                                  0.1s
>  ✔ Container muse-muse-1  Created                                                                                  0.0s
> Attaching to muse-1
> muse-1  | 2024-07-12T19:51:19.172Z agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::] create, timeout 300001ms
> muse-1  | 2024-07-12T19:51:19.673Z agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::](requests: 1, finished: 1) free
> muse-1  | 2024-07-12T19:51:19.832Z agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::] reset timeout to 300001ms
> muse-1  | 2024-07-12T19:51:19.832Z agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::](requests: 2, finished: 1) reuse on addRequest, timeout 300001ms
> muse-1  | 2024-07-12T19:51:19.917Z agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::](requests: 2, finished: 2) free
> muse-1  | 2024-07-12T19:51:19.932Z agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::] reset timeout to 300001ms
> muse-1  | 2024-07-12T19:51:19.932Z agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::](requests: 3, finished: 2) reuse on addRequest, timeout 300001ms
> muse-1  | 2024-07-12T19:51:20.991Z agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::](requests: 3, finished: 3) free
> muse-1  | 2024-07-12T19:51:20.999Z agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::] reset timeout to 300001ms
> muse-1  | 2024-07-12T19:51:20.999Z agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::](requests: 4, finished: 3) reuse on addRequest, timeout 300001ms
> muse-1  | 2024-07-12T19:51:21.121Z agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::](requests: 4, finished: 4) free
> muse-1  | 2024-07-12T19:51:21.139Z agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::] reset timeout to 300001ms
> muse-1  | 2024-07-12T19:51:21.139Z agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::](requests: 5, finished: 4) reuse on addRequest, timeout 300001ms
> muse-1  | 2024-07-12T19:51:21.200Z agentkeepalive sock[0#registry.npmjs.org:443::::::::true:::::::::::::](requests: 5, finished: 5) free
> ```

This is normal output for my method, its just downloading the new packages. It could take a while depending on the quality of your connection.

> 
> And this is the output when I try it locally:
> 
> 
> ```
> npm install @distube/ytdl-core@latest && sed -i 's%ytdl-core%@distube/ytdl-core%g' src/services/player.ts && tini -- yarn start
> npm WARN EBADENGINE Unsupported engine {
> npm WARN EBADENGINE   package: 'http-cookie-agent@6.0.5',
> npm WARN EBADENGINE   required: { node: '>=18.0.0' },
> npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
> npm WARN EBADENGINE }
> npm WARN EBADENGINE Unsupported engine {
> npm WARN EBADENGINE   package: 'undici@6.19.2',
> npm WARN EBADENGINE   required: { node: '>=18.17' },
> npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
> npm WARN EBADENGINE }
> 
> up to date, audited 716 packages in 2s
> 
> 166 packages are looking for funding
>   run `npm fund` for details
> 
> 27 vulnerabilities (1 low, 9 moderate, 15 high, 2 critical)
> 
> To address issues that do not require attention, run:
>   npm audit fix
> 
> To address all issues possible (including breaking changes), run:
>   npm audit fix --force
> 
> Some issues need review, and may require choosing
> a different dependency.
> 

Your version of node is too old. It has been unsupported for quite a while now, you should upgrade 😄

**Comment by EugeneLeclerc** [comment]
> Another workaround while waiting for #1042 to be merged, is to use `codetheweb/muse:pr-1042` or `codetheweb/muse:584bb17b73594b8fcfad6a9aefb2abe3d17f3ce8` instead of `codetheweb/muse:latest`.
> 
> Works fine for me.

Did not know PR published a docker image, nice. This is definetely better than my workaround 😉

**Comment by EugeneLeclerc** [comment]
> Yep, was on the wrong node version because it's recommended in the README:
> 
> > Node.js (16.x is recommended because it's the current LTS version)

Yeah the README is wrong, Node 16 has not been LTS for quite a while, this should be updated too I guess ^^

**Comment by Heiwa03** [comment]
> codetheweb/muse:pr-1042

can confirm switching to `codetheweb/muse:pr-1042` works

**Comment by im-trisha** [comment]
I get "🚫 ope: Sign in to confirm you’re not a bot" using `codetheweb/muse:pr-1042`

**Comment by danexrc** [comment]
I also get the same error! Is there anyway to run the bot via a proxy/vpn to get around the issue?

I'm running via Docker and it isn't working.

**Comment by Indysaurus** [comment]
Switching to codetheweb/muse:pr-1042 running via docker resolved the issue for me.

**Comment by Dan-Mizu** [comment]
Getting the following error on codetheweb/muse:pr-1042 with the same issue as before: no song audibly playing.

```
/********************************************************************************************************************************************************************************************************

failed at func parseItem: Cannot read properties of undefined (reading 'browseEndpoint')

pls post the the files in /usr/app/node_modules/ytsr/dumps to https://github.com/TimeForANinja/node-ytsr/issues

os: linux-x64, node.js: v18.20.4, ytsr: 3.8.4

********************************************************************************************************************************************************************************************************\

Error: type lockupViewModel is not known

    at parseItem (/usr/app/node_modules/ytsr/lib/parseItem.js:83:13)

    at catchAndLogFunc (/usr/app/node_modules/ytsr/lib/parseItem.js:90:12)

    at module.exports (/usr/app/node_modules/ytsr/lib/parseItem.js:119:46)

    at /usr/app/node_modules/ytsr/lib/main.js:53:34

    at Array.map (<anonymous>)

    at module.exports (/usr/app/node_modules/ytsr/lib/main.js:53:25)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at KeyValueCacheProvider.wrap (/usr/app/src/services/key-value-cache.ts:53:20)

    at async run (file:///usr/app/node_modules/p-queue/dist/index.js:109:36)

/********************************************************************************************************************************************************************************************************

failed at func parseItem: type lockupViewModel is not known

pls post the the files in /usr/app/node_modules/ytsr/dumps to https://github.com/TimeForANinja/node-ytsr/issues

os: linux-x64, node.js: v18.20.4, ytsr: 3.8.4

********************************************************************************************************************************************************************************************************\

(node:9) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 stateChange listeners added to [Networking]. Use emitter.setMaxListeners() to increase limit

(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by celliern** [comment]
> > I get "🚫 ope: Sign in to confirm you’re not a bot" using `codetheweb/muse:pr-1042`
> 
> Same thing is happening to me

Same thing here, one day of working bot then that error occurred

**Comment by Stealthii** [comment]
> I get "🚫 ope: Sign in to confirm you’re not a bot" using `codetheweb/muse:pr-1042`

This is a wider issue affecting many other bots using Youtube's API.

* https://github.com/jagrosh/MusicBot/issues/1588
* https://github.com/play-dl/play-dl/issues/370
* https://github.com/eritislami/evobot/issues/1638
* https://github.com/mps-youtube/yewtube/issues/1276
* https://github.com/ViewTube/viewtube/issues/2935

It seems like the cobalt client might have solved it using OAuth tokens. That might also work for this project.
https://github.com/imputnet/cobalt/issues/551

**Comment by codetheweb** [comment]
Apologies for the delay here!

**Comment by xxtensazenxx** [comment]
Its still not working for me :( can anyone confirm it the bot is functional again yet?

**Comment by Heiwa03** [comment]
> Its still not working for me.  Can anyone confirm it the bot is functional again yet? or is it still dead.
> I try to queue up a song still, bot joins channel, says queue is empty, nothing plays, and then the bot leaves.
> 
> trying "codetheweb/muse:pr-1042" did nothing for me either.
> 
> my logs don't give much insight 
> 
> `WARNING: @distube/ytdl-core is out of date! Update with "npm install @distube/ytdl-core@latest".
> WARNING: Could not parse n transform function.
> Please report this issue with the "1722725695394-base.js" file on https://github.com/distubejs/ytdl-core/issues.`

I'm on you with this one. I even tried the latest commit and it only plays some songs. I think bots on discord are dead for good.
