### ISSUE TITLE
Bot will not play music

### ISSUE THREAD

**Issue by TheTanker** [codetheweb/muse#1047]
**What's happening?**
The bot will not play music. It doesnt give me any errors. When i add a song to the queue, it shows the song has been added to the queue, then nothing plays. I have uninstalled and reinstalled the container and that has not fixed it.

**Runtime**
I'm running Muse:
- [ ] Directly from the cloned repository
- [ X] Inside a Docker container (unraid)
- [ ] Something else (please elaborate)

**Versions**
- Muse: Latest

**Comment by freerainboxbox** [comment]
Same issue here, seems like it only applies to certain videos.

**Comment by jamespandaz** [comment]
Maybe have a look at #1037 that could help

TL:DR using latest has a broken dependency in it, pull docker image `codetheweb/muse:pr-1042` instead of `codetheweb/muse:latest` and run that

**Comment by codetheweb** [comment]
Fixed in https://github.com/codetheweb/muse/releases/tag/v2.9.0. Apologies for the delay!

**Comment by kezzkezzkezz** [comment]
:pr-1042 and 2.9.0 both refuse to play any music and give no errors
