### ISSUE TITLE
Muse docker container crashes

### ISSUE THREAD

**Issue by SublimePhotographyuk** [codetheweb/muse#1048]
Hey guys,
when trying to play music through the discord bot, the bot joins the call no music plays. then the docker container (running in unraid) crashes. I messed with another version which worked for a few seconds then the  sound would wobble and again crash the discord bot.
any ideas on how I would fix this?

I'm newish to the home lab scene so I apologise if I'm a little slow 

Directly from the cloned repository
[ X] Inside a Docker container (unraid)

ps idk if this would help but im currently running on the latest version (codetheweb/muse)

**Comment by codetheweb** [comment]
Fixed in https://github.com/codetheweb/muse/releases/tag/v2.9.0.
