### ISSUE TITLE
Unable to play youtube videos

### ISSUE THREAD

**Issue by merlin3of5** [codetheweb/muse#1052]
**What's happening?**
Unable to play youtube using latest Muse container. 

Example song:  https://www.youtube.com/watch?v=sFmns-KUc94

**Logs**
```
WARNING: @distube/ytdl-core is out of date! Update with "npm install @distube/ytdl-core@latest".

WARNING: Could not parse n transform function.

Please report this issue with the "1722469944097-base.js" file on https://github.com/distubejs/ytdl-core/issues.
```

**Runtime**
I'm running Muse:
- [ ] Directly from the cloned repository
- [x] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: latest (Running version 2.9.0 built on 7/18/2024 (commit 94c24263ba58057e3fa4023339541aae0fc2487b))
- Docker (if applicable): 24.0.7
- OS: Docker running on Ubuntu 22.04.4 LTS 
- Node.js: (if running outside the Docker container)
- ffmpeg: (if running outside the Docker container, 4.1 or later is required)

**Comment by HachijoTohya** [comment]
I am also having issues getting videos to play. Same log message as well

`WARNING: @distube/ytdl-core is out of date! Update with "npm install @distube/ytdl-core@latest".
WARNING: Could not parse n transform function.
Please report this issue with the "1722471864905-base.js" file on https://github.com/distubejs/ytdl-core/issues.
`

Running muse inside a docker container

Muse: Running version 2.9.0 built on 7/18/2024 (commit 94c24263ba58057e3fa4023339541aae0fc2487b)
Docker: 26.1.0 build 9714adc
OS: Ubuntu jammy 22.04

**Comment by cwerdna19** [comment]
Fixed by using a different releast of ytdlp
https://github.com/distubejs/ytdl-core/issues/50#issuecomment-2261255572

**Comment by Zimnior12** [comment]
Same issue. Using docker.

```
WARNING: @distube/ytdl-core is out of date! Update with "npm install @distube/ytdl-core@latest".
WARNING: Could not parse n transform function.
Please report this issue with the "1722522169510-base.js" file on https://github.com/distubejs/ytdl-core/issues.
```

Wanted to try out the bot for the first time and that's what greeted me lol.

**Comment by merlin3of5** [comment]
Tried running "codetheweb/muse:dca6406a25d10bf05eecadbb3f5651d7b02bf725". While the error about ytdl-core has gone away, I am still unable to get the muse bot to work with youtube. I enabled debug, but I am unable to find any errors that seem relevant. I am going to poke around my API settings and see if I can find anything. 

Note: Spotify works, its just youtube that fails to play.

**Comment by TwitchBluelow** [comment]
Just connect to the command line and update ytdl with 

`npm install @distube/ytdl-core@latest`.

Fixed it for me

**Comment by merlin3of5** [comment]
So, did a little more testing and youtube playback will work for some videos, but not others. Not sure if anyone else that is have issues can replicate my findings below.

Does not work
https://www.youtube.com/watch?v=sFmns-KUc94
https://www.youtube.com/watch?v=BK_zIc_dVH0
https://www.youtube.com/watch?v=yNmqX5BlAD8
https://www.youtube.com/watch?v=K-Wyl54Kv6M
https://www.youtube.com/watch?v=iWli-sMTs3s
https://www.youtube.com/watch?v=fh8o8MqLlIg

Works
https://www.youtube.com/watch?v=aVmbeJyfs2s
https://www.youtube.com/watch?v=tBS4XvKdR6U
https://www.youtube.com/watch?v=oyEKFkFrDGg

**Comment by cwerdna19** [comment]
@merlin3of5 Update your package.json line 93 to:
`"@distube/ytdl-core": "^4.13.7",`

It's just an issue with ytdl-core

**Comment by italianjunky** [comment]
Updating ytdl-core did not work for me, but some songs work. What I presume though, is that those are cached songs and therefore still work. Also for some weird reason when trying to play a spotify song it tries it with youtube first and never uses Spotify.

**Comment by satwikpadhy** [comment]
Updating the ytdl-core did not work for me as well. The bot joins the the voice channel but stays silent. Then exits the voice channel after a bit

**Comment by cwerdna19** [comment]
Just want to say it works fine for me. I'm running muse with node and not docker. I just did an npm i to get the latest version of ytdl-core. I'm listening to a song I've not played before now.

**Comment by cwerdna19** [comment]
There is a new ytdl release https://github.com/distubejs/ytdl-core/releases/tag/4.14.0
On the previous release, 4.13.7, some songs also did not work for me. Those songs that did not work appear to now work in 4.14.0

Note I'm running muse without Docker but I don't think it really makes a difference.
