### ISSUE TITLE
Problem with playing a song

### ISSUE THREAD

**Issue by jos135** [codetheweb/muse#1057]
When i start the bot using docker compose it will start just fine. When i try to play a song using youtube i get a error
Spotify result is the same problem but without the logging.

**Logs**

WARNING: @distube/ytdl-core is out of date! Update with "npm install @distube/ytdl-core@latest".
WARNING: Could not parse n transform function
Please report this issue with the "1722622479844-base.js" file on https://github.com/distubejs/ytdl-core/issues..
```



**Runtime**
I'm running Muse:
- [ ] Directly from the cloned repository
- [X] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: 2.9.0
- Docker (if applicable): 1.5-2  with compose 1.29.2
- OS: debian
- Node.js: (if running outside the Docker container)
- ffmpeg: (if running outside the Docker container, 4.1 or later is required)

**Comment by erdanilevicius** [comment]
I had the same issue, with running it on docker. It works fine when running with nodeJS the only exception is some erros from  ytdl-core for private/age restricted videos that are not private. Then the bot for me just either shuts itself off because of these errors.

**Comment by xxtensazenxx** [comment]
Same issue here
