### ISSUE TITLE
Bot will not play any music (Docker) - ongoing issues 

### ISSUE THREAD

**Issue by xxtensazenxx** [codetheweb/muse#1059]
The bot will not play anything from Youtube. The bot joins when you add a song and is silent. The queue remains empty if you check it. Then the bot leaves after about a minute. Its completely unfunctional for me and has been for over a month.

![image](https://github.com/user-attachments/assets/eee8f846-0b33-47c5-a22a-57a12b3c67c6)

**Additional context**
Running on docker. Here's my compose file (censored  the tokens ofc)
`version: '3.4'

services:
  muse:
    image: codetheweb/muse:latest
    restart: always
    volumes:
      - /home/matt/data/muse:/data
    environment:
      - DISCORD_TOKEN=XXXXX
      - YOUTUBE_API_KEY=XXXXX
      - SPOTIFY_CLIENT_ID=XXXXX
      - SPOTIFY_CLIENT_SECRET=XXXXX
`

**Runtime**
I'm running Muse:
- [ ] Directly from the cloned repository
- [X ] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: 2.9.0
- Docker (if applicable): Docker version 27.0.2, build 912c1dd
- OS: Debian 12
- Node.js: (if running outside the Docker container) (docker)
- ffmpeg: (if running outside the Docker container, 4.1 or later is required) (docker)

> Running version 2.9.0 built on 7/18/2024 (commit 94c24263ba58057e3fa4023339541aae0fc2487b)
🔧 Need help? https://github.com/codetheweb/muse/discussions/new
🐛 Bug? https://github.com/codetheweb/muse/issues/new
✨ New feature? https://github.com/codetheweb/muse/issues/new
☕ Discussion? https://github.com/codetheweb/muse/discussions/new
💰 Help me? https://www.paypal.me/codetheweb https://github.com/sponsors/codetheweb
- Applying database migrations...
✔ Database migrations applied.
- 📡 connecting to Discord...
✔ Ready! Invite the bot with https://discordapp.com/oauth2/authorize?client_id=1207894300466216962&scope=bot%20applications.commands&permissions=36700160
WARNING: @distube/ytdl-core is out of date! Update with "npm install @distube/ytdl-core@latest".
WARNING: Could not parse n transform function.
Please report this issue with the "1722727054158-base.js" file on https://github.com/distubejs/ytdl-core/issues

**Comment by WarrtedBubble** [comment]
Same issues over here, i think its been not working for a hot sec. 

WARNING: @distube/ytdl-core is out of date! Update with "npm install @distube/ytdl-core@latest".

WARNING: Could not parse n transform function.

Please report this issue with the "1722733873847-base.js" file on https://github.com/distubejs/ytdl-core/issues.

**Comment by WarrtedBubble** [comment]
This fixed it for me, 

Connect to the docker Container's shell by docker exec -it [containerID] sh

Once your at the shell just update the spicy thingy npm install @distube/ytdl-core@latest

Stop & and Start the docker container

**Comment by xxtensazenxx** [comment]
> npm install @distube/ytdl-core@latest

that fixed it for me too.... weird. Does that mean we're going to have to run this command any time they update Muse?

**Comment by kezzkezzkezz** [comment]
Tried this and still not plying anything

> npm install @distube/ytdl-core@latest

**Comment by TheIceMagmaCube** [comment]
Got the same problem!
Tried the command by using "docker run _*container_id*_"
> npm install @distube/ytdl-core@latest

Restarted the container, still not working.
My API keys are good.
