### ISSUE TITLE
Feature Request: Using a Music Bot as a Standalone Audio Server

### ISSUE THREAD

**Issue by pepek1122583** [codetheweb/muse#1061]
Would it be possible to implement a boolean option (true/false) for the bot to play audio locally?

Example:
The server running the bot would have speakers connected, and users could send links to the bot. This would be useful in an office setting

**Comment by codetheweb** [comment]
Sorry, not interested in implementing this as it's pretty out-of-scope. Maybe have Discord open on the server?
