### ISSUE TITLE
Youtube Playlists only loading 50 Videos

### ISSUE THREAD

**Issue by JoiTD** [codetheweb/muse#156]
Command: play youtubePlaylistURL
Bot loads the playlist just fine, but only up to video 50. Tested with multiple playlists.

**Comment by codetheweb** [comment]
Sorry about that.
I was too lazy when implementing to add pagination. 😅 

Fixed in 6e0d4c7, currently [building and publishing Docker image](https://github.com/codetheweb/muse/runs/2248936666?check_suite_focus=true) (will take a while).

Glad to hear other people are finding this useful!

**Comment by JoiTD** [comment]
No worries! I'm actually loving the bot, I've tried a few. Looking forward to the update!
Thanks for the rick roll btw 👍

**Comment by codetheweb** [comment]
Should be available on Docker Hub now, let me know if that fixes it.

**Comment by JoiTD** [comment]
Aye, it's working now! Thanks for the quick fix 👍
