### ISSUE TITLE
A little help needed 

### ISSUE THREAD

**Issue by LoopsFroot** [codetheweb/muse#269]
Hi 

The installation was well documented and worked great.

Now I want to actually use the bot but I'm having a little trouble. 

- Whats the default prefix?
- Can I change the prefix and how?
- Is there a !help or !command where I can see all the commands?

Thanks in advance!

**Comment by LoopsFroot** [comment]
So I tried it on a other server and here I get a private message with what channel the bot needs to listen to and what prefix to use. Why does this not work with the other server?

**Comment by LoopsFroot** [comment]
I tried everything but can seem to get it to work on the server with my friends. I deleted all unused roles and weird permissions. I just dont reviece the private message. But it works perfectly on a server were I am alone.

**Comment by codetheweb** [comment]
It sends the setup DM to the guild owner, which may not necessarily be you in a guild with friends.
