### ISSUE TITLE
help command produces error

### ISSUE THREAD

**Issue by jacob54261** [codetheweb/muse#281]
Help command produces error shown below
![image](https://user-images.githubusercontent.com/30564461/128119791-f0670df3-19e8-4f26-848b-ec62f870392c.png)

**Comment by jacob54261** [comment]
Update; issue was with the youtube API key, however, the help command still does not function as depicted above.

**Comment by codetheweb** [comment]
That's embarrassing; the help message went over the character limit at some point without me noticing. 😅

Should be fixed now, update to the latest image / pull the latest from master. Let me know if you have any other issues.
