### ISSUE TITLE
[Suggestion] Add support for local audio playback

### ISSUE THREAD

**Issue by Carbuino** [codetheweb/muse#299]
I'm not sure how difficult this would be to implement with the caching and all but it would be cool to be able to play mp3s that are in the data directory without searching the internet.

**Comment by codetheweb** [comment]
Not currently interested in implementing this, sorry. I might accept this if you prepare a high-quality PR, but I'd like to keep the scope of Muse narrow and confined to YouTube / Spotify / other streaming sites. Adding support for local files would require a lot of structural changes to not just the code but probably the bot commands as well.
