### ISSUE TITLE
Bot will always join most popular channel, even if connected to different channel

### ISSUE THREAD

**Issue by jeyo123** [codetheweb/muse#314]
In a server with multiple VCs ($popular-vc and $connected-vc):

$popular is a Voice Channel with many users
$connected-vc is the Voice Channel the requestor is connected to, with less users than $popular-vc

Muse will always connect to the most popular VC, even if the requestor is connected to a different VC. This makes it quite annoying when running multiple instances on the same guild, as all of the music player bots end up connecting to the same VC, even if they are requested from different bound channels by different users. What I would normally expect is for the bot to bind to the same VC as the user that requested the music, even if they are connected to a less popular channel.

Would it be possible to force the bot to connect to the VC that the requestor user is connected to (i.e. the VC that the user that entered the !play command in chat is connected to)?

**Comment by codetheweb** [comment]
Interesting, I never thought of a scenario where you could run multiple instances in the same guild, just bound to different channels. I'm kinda surprised it works at all 😛.

I think this makes sense, happy to accept a PR for it otherwise you'll probably have to wait until this weekend.
