### ISSUE TITLE
that doesnt exist (spotify and youtube)

### ISSUE THREAD

**Issue by hammondses** [codetheweb/muse#323]
I'm still seeing the same issues even after updating to the new Docker container.

Is there logs somewhere that I can post or view to try to figure out what's going on?

Thanks!

**Comment by hammondses** [comment]
resolved, enabling all of the youtube APIs and generating a key from that seems to have resolved my problem

**Comment by IoIxD** [comment]
Hi, I'm having this exact same problem. By "all of the YouTube APIs", you mean the Data API v3, Reporting API, and Analytics API, right? What else am I missing?
