### ISSUE TITLE
node.js help

### ISSUE THREAD

**Issue by MaalikN** [codetheweb/muse#326]
i apologize for the inexperience, what exactly do i do at this step?

Copy .env.example to .env and populate with values

**Comment by codetheweb** [comment]
In a file explorer or a terminal window, copy the contents of the `.env.example` file into a new file called `.env` and add the required API keys.

**Comment by MaalikN** [comment]
thank you, turns out my problem was winscp wasn't actually showing hidden files so I couldn't see .env.example

**Comment by MaalikN** [comment]
is data_dir used at all?

**Comment by codetheweb** [comment]
It's used to cache audio files so Muse doesn't have to stream directly from YouTube if the song has been played before.

**Comment by MaalikN** [comment]
do i need to set up a path? how so?

**Comment by codetheweb** [comment]
If you're running directly from some kind of terminal you don't have to do anything else, Muse will automatically create the data directory for you.
