### ISSUE TITLE
bot joins but music don't work

### ISSUE THREAD

**Issue by vladineto** [codetheweb/muse#328]
I got the bot to work and joining into my server but the moment I send a play command to him he just joins the call, prints in chat the song he is going to play and nothing happens, I have ffmpeg installed and I got it to work with node.js

this is the error printed in git bash

![image](https://user-images.githubusercontent.com/90790562/133479302-48a7074e-5ce9-46d9-b07d-9d1dcf0c9ac2.png)

**Comment by codetheweb** [comment]
Could you try running with the DEBUG environment variable set to * and see if another error is logged? (`DEBUG=* node ...` for *sh shells).

Looks like an error is thrown but then the bot can't post the error because it's longer than 2000 characters. I'll have to fix that to be chunked.

**Comment by vladineto** [comment]
the only error I could find inside the DEBUG environment was this, the rest of the code looks kinda normal to me, if you want me to upload the log, I can.
![image](https://user-images.githubusercontent.com/90790562/133485368-4abb3e90-1ea3-4fb8-9041-31b59be5415f.png)

**Comment by vladineto** [comment]
never mind, i searched and found out I didn't had windows-build-tools installed

ty for your patience
