### ISSUE TITLE
Channel selection via reactions

### ISSUE THREAD

**Issue by aljaxus** [codetheweb/muse#332]
While it sounds neat it's actually rather bad - in my opinion - for the following reasons:

1. Why even bother implementing such system when there are permissions. The guild administrators should setup permissions for the bot role if they want to restrict the bot to have access only to specific channels
2. It's just another thing that can (and does) break
  2.1. Not all icons (reactions) used are implemented by Discord (see attachment bellow)

---

The "eye" icon (👁️‍🗨️) is not implemented by Discord, so it can not be added as a reaction.
![image](https://user-images.githubusercontent.com/24414483/133590788-3f9e96f7-c8a9-46f5-9741-537ea36fdfda.png)

---

I propose that the "select your channel" implementation is scrapped (left implemented so the current setups still keep working as they are intended to), but the setup process is removed and channel checking is ignored in future installations.

eg.
```
- Bot startup
- check datastore
  - get guild settings
- message is handled
  - is command
  - is guild setting channel present?
    - yes: check if command is in that channel
      - is in channel: continue
      - is not in channel, return;
    - no: continue;
```

This is also related to #331 which aims to remove the prefix setting from setup. With both issues resolved and features being implemented, the setup process will be simpler (eg. no bot-specific setup) and will make the usage more fluent.

**Comment by cheqpat** [comment]
It would be nice to remain as an option, either using the config command or with a env variable.

**Comment by codetheweb** [comment]
The idea is that you might want to have a channel dedicated to music bots, i.e. `#music-commands` or something. I agree that basing the system off of whatever channels Muse has access to might make more sense (and aligns better with the philosophy outlined in the README), although I'm not sure if that would hide slash commands for other channels or not.

**Comment by aljaxus** [comment]
> although I'm not sure if that would hide slash commands for other channels or not

Valid point. 

I guess a dirty hack that first comes to mind is list all text channels that the bot has access to in the given guild and just register commands per-channel. But this is more of a "patch" than a long-term solution.
I do not know if the globally-registred commands are also "present" in text channels that the bot does not have access to which might be the case (hopefully as it would simplify things)

**Comment by codetheweb** [comment]
Yeah, sounds like it would just require some experimentation.

**Comment by codetheweb** [comment]
This was closed by v1 with slash commands.
