### ISSUE TITLE
docker - stuck on Ready! Invite the bot with https://discordapp.com

### ISSUE THREAD

**Issue by Maltahl** [codetheweb/muse#337]
Ran the docker run as per instructed on the README but it just stuck in:
 _Ready! Invite the bot with https://discordapp.com/oauth2/authorize?client_id=XXXXXXXXX_

I see the bot is online through discord and it is added in the discord server but it is not reacting to anything i do and is not joining the discord channel

**Comment by Maltahl** [comment]
Disregard my issue. It was due to server owner not being myself... would be nice if @Manage role was enough for adding the bot to a server.

**Comment by CallMeChin** [comment]
is there any solution to this?

**Comment by codetheweb** [comment]
Currently, the server owner must follow the DMed instructions to set up Muse.

This may change in the future with slash commands.
