### ISSUE TITLE
Running

### ISSUE THREAD

**Issue by tcharleserf** [codetheweb/muse#340]
tried to execute this on Node.js "git clone https://github.com/codetheweb/muse.git && cd muse" and got syntax error.
Then i tried to execute on Git CMD and it went ok however the running problem still here, same on docker.
![image](https://user-images.githubusercontent.com/90987026/133910909-1f9c7118-6d04-46f6-9852-f0132bb69291.png)

**Comment by Sequence32** [comment]
have you added all the keys to the .env file and rebuilt the project?

if you're using npm. npm i, npm run build, npm run start. This isn't a syntax error.

**Comment by codetheweb** [comment]
Same issue as https://github.com/codetheweb/muse/issues/329, please follow that one for updates.
