### ISSUE TITLE
 ❌ no songs found

### ISSUE THREAD

**Issue by stevewas** [codetheweb/muse#341]
Hey Codetheweb,

I think I'm getting the same error as one of the other issues (315) where It won't play any more links, when I checked the GCP it says that error with the 10k cap.
<img width="789" alt="Screen Shot 2021-09-18 at 10 35 16 PM" src="https://user-images.githubusercontent.com/9499856/133913518-d4058b83-9a07-4336-a2ee-3d921dc38f85.png">
 
I was wondering if you can add ytsr to put less strain on the youtube API limit.

**Comment by stevewas** [comment]
<img width="446" alt="Screen Shot 2021-09-18 at 10 41 12 PM" src="https://user-images.githubusercontent.com/82685579/133913612-ce7b6f9d-29ec-4c5c-8070-308894e42e8e.png">
the error was bypassed when swapping to a new youtube api

**Comment by codetheweb** [comment]
Please follow https://github.com/codetheweb/muse/issues/315 for updates instead of opening a new issue. 
I said I would work on it this weekend, just haven't gotten to it yet. I work on this in my spare time and don't get paid for it, so please have some patience. 😃
