### ISSUE TITLE
Add an option to announce current song

### ISSUE THREAD

**Issue by stevewas** [codetheweb/muse#342]
Add an option to announce the current song to be messaged on the channel that is being monitered.

**Comment by codetheweb** [comment]
By announce, do you mean TTS in the voice channel or just a text message?

**Comment by stevewas** [comment]
just and text message to the default channel.

Also is it possible to add a stop command, that keeps the bot connected but just pauses the music and skips the current playing song?

**Comment by codetheweb** [comment]
Sorry, not really sure what the use case would be for that. `.pause` and `.skip` are available.

**Comment by codetheweb** [comment]
> Add an option to announce the current song to be messaged on the channel that is being monitered.

I have no immediate plans to add this but happy to accept a PR for it. 😃
