### ISSUE TITLE
Running on windows

### ISSUE THREAD

**Issue by hodgman** [codetheweb/muse#345]
In case anyone else is having the same struggle as me:

I had trouble figuring out how to get this running because there's no "installer" for ffmpeg on windows - it's just a zip of files...
But if ffmpeg isn't "installed" on your system I found that you can tell the node libraries where to find by setting the `FFMPEG_PATH` environment variable before starting node:

```
SET FFMPEG_PATH=C:\whatever\ffmpeg\bin\ffmpeg.exe
npm run start
```

**Comment by codetheweb** [comment]
Thanks for the info. I added a note to the README about it.

**Comment by gerrarrrr** [comment]
Can someone help me?
I'm trying to run it on windows 10!
Made all the process, the bot is in disc server, but when i try to make it play a song, it enter the voice channel and immediately quit.

powershell shows this error:

(node:5756) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
content: Must be 2000 or fewer in length.
    at RequestHandler.execute (C:\Users\geral\Desktop\Bot-main\muse\node_modules\discord.js\src\rest\RequestHandler.js:154:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async RequestHandler.push (C:\Users\geral\Desktop\Bot-main\muse\node_modules\discord.js\src\rest\RequestHandler.js:39:14)
    at async Client.<anonymous> (file:///C:/Users/geral/Desktop/Bot-main/muse/dist/bot.js:86:17)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5756) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5756) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by MR-UNKNOWN2000** [comment]
i tried this but it doesn't work it says
 ` SET FFMPEG_PATH=C:\ffmpeg\bin\ffmpeg.exe`
`npm run start`
`bash: SET: command not found`

**Comment by hodgman** [comment]
SET is the windows `cmd` command to set environment variables, so yeah, it won't work in `bash`.
Are you running bash on Windows, or Linux? Either way I think the equivalent there is `export`??
