### ISSUE TITLE
If you pause and unpause, the music is unpaused but bot is quiet

### ISSUE THREAD

**Issue by Hellysonrp** [codetheweb/muse#350]
If you pause and unpause any music, internally the music will be playing, but the bot will not play anything in the voice channel.
Pausing and unpausing again, or disconnecting and reconnecting the bot, makes it play the music normally again.
Here is a GIF demonstrating the behavior:

![pause-bug](https://user-images.githubusercontent.com/5438762/134078683-a061d135-7de5-4331-8753-a5f8a9b44a2e.gif)

I'm using the latest docker version.

**Comment by codetheweb** [comment]
Was able to reproduce this.

Seems that this is a [known issue](https://github.com/discordjs/discord.js/issues/5300) with certain Node.js versions. For now I've pinned the Node.js version in the Dockerfile, but we'll need to upgrade to Discord.js v13 (with better voice support) at some point (see #351).

Should be fixed now. (You can watch [this workflow run](https://github.com/codetheweb/muse/actions/runs/1255730544) to see when it's ready for consumption.)
