### ISSUE TITLE
Add support for youtube music urls

### ISSUE THREAD

**Issue by stsmith94** [codetheweb/muse#355]
https://www.music.youtube.com URLs could have the ".music" stripped in a similar manner to the exisiting URL cleaning #316 
Just a quality of life benefit for people who would prefer to use youtube music to find playlists.

eg.
https://www.music.youtube.com/playlist?list=PLphJpuK5IiCbcQK2VFqWlooBPW0ZNsxHm
becomes
https://www.youtube.com/playlist?list=PLphJpuK5IiCbcQK2VFqWlooBPW0ZNsxHm

**Comment by codetheweb** [comment]
Good idea!

This is now included in the latest version.
