### ISSUE TITLE
GPG Signed commits

### ISSUE THREAD

**Issue by cheqpat** [codetheweb/muse#356]
@udany  submitted two PRs I've been excited for (#322 and #325) but it's been over a week since the PR was made without any indication that they would be signed. Is there anyway for these PRs to be signed and merged?

**Comment by codetheweb** [comment]
They require changes beyond just signing the commits, but if you want to get them in ASAP feel free to make your own PRs based off of those. 😃

**Comment by cheqpat** [comment]
I was considering it, just didn't know if it was bad etiquette to "steal" a PR like that.
Thanks!

**Comment by udany** [comment]
I've been meaning to, but I just never got to the part of [configuring the GPG stuff](https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key) so, if you find them useful, steal them away :D
