### ISSUE TITLE
Control volume level

### ISSUE THREAD

**Issue by mariogarridopt** [codetheweb/muse#360]
I would love a way to control the default volume of the bot.
So when the bot gets in blasting music it stays a low volume and don't disturb the people already speaking.

**Comment by codetheweb** [comment]
This isn't something I currently plan on adding, but happy to accept a PR for it. 👍

**Comment by dotcf** [comment]
No pls not cause it will be annoying if a rdm user is Voluming up the bot. Just change the Volume for the bots profile!
