### ISSUE TITLE
Convert more than 50 songs at a time from Spotify

### ISSUE THREAD

**Issue by ManfredRichthofen** [codetheweb/muse#366]
![image](https://user-images.githubusercontent.com/46958197/134977733-f18d871b-c76e-41a5-a5b8-05dcf3507cfc.png)
Is it possible to allow the bot to play the whole playlist instead of just 50 songs?

**Comment by codetheweb** [comment]
Searching for songs on YT is an expensive operation, which is why it's limited to 50 songs.

I would be willing to accept a PR that makes the conversion limit a config variable instead of being hard-coded, but I have no plans to implement this myself.
