### ISSUE TITLE
Possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by lugui1998** [codetheweb/muse#372]
After letting the bot running for a while it gets slower and eventually it prints the following message to the console:

(node:2780) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 disconnect listeners added to [VoiceConnection]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2780) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit

When that happens, the bot becomes unresponsive and only works again after a restart.

The bot is on 4 guilds andI'm running this it on a raspberrypi 4b which isn't a very powerfull hardware, but it should've been more than enough to run a discord bot. It has a good high speed internet connection and is running on the latest node version.

**Comment by codetheweb** [comment]
@Hellysonrp were you still seeing this with your changes?

I updated the linked PR so that's ready to merge if this is still happening with v13.

**Comment by Hellysonrp** [comment]
Yes, it still happens with v13.
Merging this PR solves the issue.

**Comment by codetheweb** [comment]
Cool, thanks.
