### ISSUE TITLE
A little help make it running?

### ISSUE THREAD

**Issue by gerrarrrr** [codetheweb/muse#374]
whenever i try to run the bot this appears:
Running on windows 10, node version 12.13 (downgraded because the newer version do not build @discordjs/opus properly)

C:\Users\geral\Desktop\Bot-main\muse-master>set ffmpeg_path=C:\ffmpeg\bin\ffmpeg.exe

C:\Users\geral\Desktop\Bot-main\muse-master>npm run start

> muse@0.1.0 start C:\Users\geral\Desktop\Bot-main\muse-master
> node dist/index.js

C:\Users\geral\Desktop\Bot-main\muse-master\dist\index.js:1
import makeDir from 'make-dir';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:892:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! muse@0.1.0 start: `node dist/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the muse@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\geral\AppData\Roaming\npm-cache\_logs\2021-10-04T17_27_29_260Z-debug.log

C:\Users\geral\Desktop\Bot-main\muse-master>

**Comment by codetheweb** [comment]
You'll need to use a newer Node.js version. v14 should work (and build opus) just fine.

**Comment by gerrarrrr** [comment]
Installed Node.js v.14, it worked, but:
the bot enter in the voice chat and immediatel quit
cmd shows:

D:\Geraldo\Bot-main\muse-master>SET FFMPEG_PATH=C:\ffmpeg\bin\ffmpeg.exe

D:\Geraldo\Bot-main\muse-master>npm start

> muse@0.1.0 start D:\Geraldo\Bot-main\muse-master
> node dist/index.js

Ready! Invite the bot with--------

(node:7880) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
content: Must be 2000 or fewer in length.
    at RequestHandler.execute (D:\Geraldo\Bot-main\muse-master\node_modules\discord.js\src\rest\RequestHandler.js:154:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async RequestHandler.push (D:\Geraldo\Bot-main\muse-master\node_modules\discord.js\src\rest\RequestHandler.js:39:14)
    at async Client.<anonymous> (file:///D:/Geraldo/Bot-main/muse-master/dist/bot.js:86:17)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7880) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7880) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by codetheweb** [comment]
Can you please check out the `bugfix/only-add-listeners-once` and try again? The bot should then post an error message.

**Comment by gerrarrrr** [comment]
> Can you please check out the `bugfix/only-add-listeners-once` branch and try again? The bot should then post an error message.

worked perfectly! Thank you very much!
