### ISSUE TITLE
Bot randomly stops streaming audio

### ISSUE THREAD

**Issue by JC-Array** [codetheweb/muse#389]
When playing audio from youtube, I found the bot will randomly stop streaming the audio into the voice channel.  When this happens the bot will stay in the channel and sending the queue command shows the time stamp continuing to increase.  I've found this is repeatable for long (50 minutes) videos, though has occasionally happened on much shorter videos as well.  

After searching for the issue, I think it is the result of some dynamic between ffmpeg and fs-capacitor, where ffmpeg fills fs-capacitor buffer and subsequently will stop writing to the buffer.  This is followed by the read stream catching up and stopping as a result of no new data being added into the buffer.

Troubleshooting this, I found added '-re' to the [ffmpegInputOptions](https://github.com/codetheweb/muse/blob/master/src/services/player.ts#L365) resolved the issue.  This seems to align with [FFmpeg's streaming guide](https://trac.ffmpeg.org/wiki/StreamingGuide).

With this change it also seems like the fs-capacitor can be removed as a dependency, but I am not sure the role it plays in this code.

**Comment by codetheweb** [comment]
@JC-Array added the `-re` flag, should be fixed now.

@Hellysonrp that sounds unrelated and would likely be fixed by upgrading to the latest Discord.js version: https://github.com/codetheweb/muse/issues/351.
