### ISSUE TITLE
If a song is played, then disconnected, calling play with a new song does not reconnect the bot to the voice channel

### ISSUE THREAD

**Issue by nmarks413** [codetheweb/muse#394]
I recently complied the bot, and found this issue when testing it with my friends. Removing the if statement on line 60 to just be 
```
if (player.voiceConnection === null) {
      await player.connect(targetVoiceChannel);

      await player.play();
   }
```
seemed to fix the problem but i do not know if this causes more issues

**Comment by AaronWiora** [comment]
Any updates on this?
I'm experiencing the same issue on my server and I'm not sure if I understand the whole situation.
 If I do what the title says the bot is rendered unusable permanently and there is no way we can play music?

**Comment by codetheweb** [comment]
I don't think it becomes unusable, you just have to send two `.play` commands to get it working again.

**Comment by BlueHairMinerBoy** [comment]
Having the same issue - if someone issues a `disconnect` command or everyone leaves the chat the bot doesn't join the voice channel back unless the bot is restarted.

**Comment by GorlikItsMe** [comment]
I have a similar issue
I leave the channel (and bot also leave)
but when I join back and send `!play url` bot add a song to queue but don't appear in the channel
bot appear in the channel only when I send empty `!play` command

I think there is missing check "is bot in voice channel"

**Comment by codetheweb** [comment]
This should now be fixed, please try it out and let me know if you believe the behavior should be further modified.

(If you use the container image, wait for it to [build and push](https://github.com/codetheweb/muse/actions/runs/1570115084) before re-pulling.)
