### ISSUE TITLE
Bot dies trying to delete the same cache file more than one time

### ISSUE THREAD

**Issue by Hellysonrp** [codetheweb/muse#419]
Last week past without problems with the new cache system, but this week this happened three times already.
![Screenshot_26](https://user-images.githubusercontent.com/5438762/144294537-1b09987a-9389-4514-8318-1434e76a880c.png)

Investigating the issue, I found that because of the way async/await works, `evictOldestIfNecessary` may be called concurrently.
https://github.com/codetheweb/muse/blob/9afca25866830dacc668b1861bab5c12260de639/src/services/file-cache.ts#L89-L103

An example would be:
Line 97 is called (`await oldest.destroy();`), which may cause Line 90 to execute in another of the function calls, resulting in Line 98 executing again for the same file.

This problem occurs with more frequency if the bot is used in more than one guild (mine is used in three guilds, most of the time in at least two guilds simultaneously).

---

I guess I was just lucky enough last week 😅 

I'm already working on a fix.
I'll be testing the fix until this weekend and will open a PR if it works.

My WIP fix can be found in [this branch in my fork](https://github.com/Hellysonrp/muse/tree/mutex). I don't guarantee it's working though.

**Comment by codetheweb** [comment]
Ah, that makes sense--thanks. 

Looks like you're using mutexes. Would like to use p-limit or p-queue if possible since those are already dependencies.

**Comment by Hellysonrp** [comment]
> Would like to use p-limit or p-queue if possible since those are already dependencies.

I'll take a look into it.

**Comment by Hellysonrp** [comment]
I've changed it to use `p-queue`.
