### ISSUE TITLE
Stay after queue ends

### ISSUE THREAD

**Issue by Makifun** [codetheweb/muse#481]
Not sure how to tag as enhancement but I would like a way to set how long the bot stays in the channel when finished playing a song.

As it is now the bot leaves when done playing something but it would be great if it would stay for a minute or so(less annoying leave and join sounds).

**Comment by codetheweb** [comment]
A PR was started for this but never finished: https://github.com/codetheweb/muse/pull/322

Happy to accept a new one. :)

**Comment by codetheweb** [comment]
Released in [v1.1.0](https://github.com/codetheweb/muse/releases/tag/v1.1.0).
