### ISSUE TITLE
When playing a Spotify playlist, one song lookup failure fails the whole playlist

### ISSUE THREAD

**Issue by JeremySB** [codetheweb/muse#487]
I believe this bug was introduced in v0.3.2 in https://github.com/codetheweb/muse/commit/65dd43ac6807d43f1af19975d4f0404a487cb71f

I think the root cause is from youtubeVideoSearch() now throwing instead of returning null, so Spotify playlist searches fail if only one song lookup fails. https://github.com/codetheweb/muse/blob/8041586c31dbfcaf4f2b12109e5dcfac27f61892/src/services/get-songs.ts#L258

Can likely reproduce with an attempt to play a good-sized Spotify playlist with more obscure songs. I would submit a PR but haven't done node work in a while and don't have the environments setup...

Thanks

**Comment by codetheweb** [comment]
Released in [v0.5.1](https://github.com/codetheweb/muse/releases/tag/v0.5.1).
