### ISSUE TITLE
Upgraded version and its not working

### ISSUE THREAD

**Issue by unixbird** [codetheweb/muse#504]
I upgraded to the latest version and have done what was recommended by kicking and readding the bot but it still does not respond to commands. Is there anything else that I need to do?

**Comment by unixbird** [comment]
#472 

Read this and was unable to get it working

**Comment by codetheweb** [comment]
The server owner will need to set what role has access to the bot using `/config set-role`.

**Comment by unixbird** [comment]
> 

attempted this and nothing pops up or happens

**Comment by unixbird** [comment]
These are the actual errors im getting with the container failing continuously 

`
      {

        name: 'seek',

        description: 'seek to a position from beginning of song',

        options: [

          {

            choices: undefined,

            autocomplete: undefined,

            type: 3,

            name: 'time',

            description: 'time to seek',

            required: true

          }

        ],

        default_permission: undefined

      },

      {

        name: 'shuffle',

        description: 'shuffle the current queue',

        options: [],

        default_permission: undefined

      },

      {

        name: 'skip',

        description: 'skip the next songs',

        options: [

          {

            max_value: undefined,

            min_value: undefined,

            choices: undefined,

            autocomplete: undefined,

            type: 4,

            name: 'number',

            description: 'number of songs to skip [default: 1]',

            required: false

          }

        ],

        default_permission: undefined

      },

      {

        name: 'unskip',

        description: 'go back in the queue by one song',

        options: [],

        default_permission: undefined

      }

    ]

  }

}

file:///usr/app/node_modules/execa/lib/error.js:59

		error = new Error(message);

		        ^


Error: Command failed with exit code 1: node --experimental-json-modules dist/src/scripts/migrate-and-start.js

    at makeError (file:///usr/app/node_modules/execa/lib/error.js:59:11)

    at handlePromise (file:///usr/app/node_modules/execa/index.js:119:26)

    at processTicksAndRejections (node:internal/process/task_queues:96:5)

    at async file:///usr/app/dist/src/scripts/run-with-database-url.js:5:5 {

  shortMessage: 'Command failed with exit code 1: node --experimental-json-modules dist/src/scripts/migrate-and-start.js',

  command: 'node --experimental-json-modules dist/src/scripts/migrate-and-start.js',

  escapedCommand: 'node --experimental-json-modules "dist/src/scripts/migrate-and-start.js"',

  exitCode: 1,

  signal: undefined,

  signalDescription: undefined,

  stdout: undefined,

  stderr: undefined,

  failed: true,

  timedOut: false,

  isCanceled: false,

  killed: false

}

error Command failed with exit code 1.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

yarn run v1.22.15

$ npm run env:set-database-url -- node --experimental-json-modules dist/src/scripts/migrate-and-start.js


> muse@1.0.0 env:set-database-url

> node dist/src/scripts/run-with-database-url.js "node" "--experimental-json-modules" "dist/src/scripts/migrate-and-start.js"


(node:53) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time

(Use `node --trace-warnings ...` to show where the warning was created)

========================================

========================================

================= muse =================

========================================

=========== Made with 🎶 by ============

==== https://github.com/codetheweb =====

========================================

========================================


Running version 1.0.0 built on Invalid Date (commit unknown)


🔧 Need help? https://github.com/codetheweb/muse/discussions/new

🐛 Bug? https://github.com/codetheweb/muse/issues/new

✨ New feature? https://github.com/codetheweb/muse/issues/new

☕ Discussion? https://github.com/codetheweb/muse/discussions/new

💰 Help me? https://www.paypal.me/codetheweb https://github.com/sponsors/codetheweb



- Applying database migrations...

✔ Database migrations applied.

- 📡 connecting to Discord...`

**Comment by unixbird** [comment]
I see these lines here and a odd lack of a discord invite link. 

muse_muse.1.ilqejpwqn08v@seraphim    | 
muse_muse.1.ilqejpwqn08v@seraphim    | D[50001]: Missing Access
muse_muse.1.ilqejpwqn08v@seraphim    |     at C.runRequest (file:///usr/app/node_modules/@discordjs/rest/dist/index.mjs:7:557)
muse_muse.1.ilqejpwqn08v@seraphim    |     at processTicksAndRejections (node:internal/process/task_queues:96:5)

Do i need to redo something in the API?

**Comment by unixbird** [comment]
Alright well thanks to the previous error I tested it by making a new Bot in discord Dev and was able to get everything working by updating the yaml with the new info.
