### ISSUE TITLE
command /config set-wait-after-queue-empties: unknown subcommand in v1.1.0

### ISSUE THREAD

**Issue by Xenomer** [codetheweb/muse#517]
Unable to set the wait value because the config subcommand is not matched.

Essentially a typo in [/src/commands/config.ts:88](https://github.com/codetheweb/muse/blob/4dbb55a72119a61033d2df6e8cf46f5eaa7bba15/src/commands/config.ts#L88)

**Comment by codetheweb** [comment]
Whoops, thanks. Fixed in [v1.1.1](https://github.com/codetheweb/muse/releases/tag/v1.1.1).
