### ISSUE TITLE
Not able to play anything from Youtube

### ISSUE THREAD

**Issue by unixbird** [codetheweb/muse#529]
It seems i can query and play a song with Spotify but cannot get it to work with youtube searches. I am receiving said error in the container

`daddystunes_muse.1.ona9ghoq3qa4@racky    |   addedInChannelId: '944391407303528508',
daddystunes_muse.1.ona9ghoq3qa4@racky    |   requestedBy: '392886235909193729'
daddystunes_muse.1.ona9ghoq3qa4@racky    | }
daddystunes_muse.1.ona9ghoq3qa4@racky    | Error: ffmpeg exited with code 1: https://rr3---sn-q4flrn7r.googlevideo.com/videoplayback?expire=1645254120&ei=iEEQYorwGL2H_tcP4bOxcA&ip=75.33.229.80&id=o-AOx2lDo3IUBfHTBZofjvR16X0-sKKYKo269vxO6XMhTi&itag=251&source=youtube&requiressl=yes&mh=9X&mm=31%2C29&mn=sn-q4flrn7r%2Csn-q4fl6nz6&ms=au%2Crdu&mv=m&mvi=3&pl=19&initcwndbps=1127500&vprv=1&mime=audio%2Fwebm&ns=f6Izam3-I88zk2Z872nguIgG&gir=yes&clen=3303016&dur=217.101&lmt=1644376661884799&mt=1645232212&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=4532434&n=oTyapPebzn3GZqqvW&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgDzwKz5mVGtrsogocA10moGSXYsjdQbnGR3x_GAHkFiICIHjWDWj_OtfekzIKb34iPx6BNkl_mh1590DR5OyPVIJB&sig=AOq0QJ8wRgIhAIf-r03e5CWKt7LrzxzXt97OjkWXyj0k_O5Qp6CB4G8jAiEAzvrviPcTYkxbA6m5gC0KPJTylSoyq2ihLjUGNzKobvQ%3D: Server returned 403 Forbidden (access denied)
daddystunes_muse.1.ona9ghoq3qa4@racky    | 
daddystunes_muse.1.ona9ghoq3qa4@racky    |     at ChildProcess.<anonymous> (/usr/app/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
daddystunes_muse.1.ona9ghoq3qa4@racky    |     at ChildProcess.emit (node:events:390:28)
daddystunes_muse.1.ona9ghoq3qa4@racky    |     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
`

and this error in Discord

 'ope: no songs found'

Whats going on?

**Comment by codetheweb** [comment]
To me that looks like Google is blocking playback of YouTube videos for you.

Are you sure it works 100% of the time with Spotify but never with YouTube? When given a Spotify source Muse just searches YouTube for the corresponding tracks and plays those.

**Comment by unixbird** [comment]
@codetheweb Just tested it and yes every query with Spotify as the selection works 100% without the no songs found error. 

I was also questioning why spotify was working vs youtube as I noticed thats what the spotify searches did. I just tried youtube URLs those actually do work so just querying via youtube doesnt work at all

**Comment by codetheweb** [comment]
Doing `/play query:a cool song` goes through the exact same flow as `/play query:https://spotify.com/track/a-cool-song` so there's probably rate limiting or something else at play. I'd wait a day or two and try again.

Also note that successful API responses are cached (1 hour by default) which could also explain the divergence in behavior. Run `yarn cache:clear-key-value` if you want to clear the cache.

I just released v1.1.2 which bumps some of the dependencies. I doubt it'll fix your problem but please upgrade and see what happens.

**Comment by unixbird** [comment]
Alright so I did stop using it for a bit and the container got updated now it looks like it's working. Not quite sure what actually fixed it but it now allows me to play youtube without throwing a fit
