### ISSUE TITLE
Commands grayed out

### ISSUE THREAD

**Issue by W0lfyZRex** [codetheweb/muse#535]
When I start the bot and then invite it with the url it gives me, the commands work fine and I can play music but if I were to stop the bot and then start it again, the commands become grayed out and I cannot use them at all.

![image](https://user-images.githubusercontent.com/66094336/155161307-f4c3b41f-dd6c-47b9-82df-4b8cdc85695e.png)

The bot is still online and there are no errors at all.

**Comment by codetheweb** [comment]
What role is Muse currently set to listen to? (`/config get`)

**Comment by W0lfyZRex** [comment]
None, that is probably the issue. I thought that "allowed to use the bot" meant skipping perms or something. It works after restarting now, thank you.
