### ISSUE TITLE
Allow non-server owner to set up bot

### ISSUE THREAD

**Issue by AleAlejandrok** [codetheweb/muse#545]
Is it possible to allow the bot owner or people with an administrative role on the server to set up the music bot. The issue become apparent when we have a small discord we want to use it in but the server owner isn't readily available to add in the bot (Given I already have bot perms it's not without permission).

**Comment by codetheweb** [comment]
The tradeoff with adding this is that the bot will need audit log permissions to see who invited it. Enough users have asked for this that it might make sense though. 

Let me know if that would work and I can see what it'd take to implement this.

**Comment by DVDIsDead** [comment]
as an admin/mod for multiple servers. this would solve the "im paying you to do this stuff" talk when contacting them to set up the bot.
