### ISSUE TITLE
Bot is showing error 403 

### ISSUE THREAD

**Issue by Khaled1066** [codetheweb/muse#553]
Hello

So I manged to get the bot working and invited to discord server but when I want to play music form youtube i get this error

![image](https://user-images.githubusercontent.com/26714670/157856402-deca879d-b44c-4662-8b1f-a8bf9fdc134b.png)

 and for spotify 

![image](https://user-images.githubusercontent.com/26714670/157856583-84577e7c-3c99-42ae-b0d9-685e067221d6.png)

any help?

**Comment by Khaled1066** [comment]
I do not know how to get the log, as the bot is showing online and nothing showed in the terminal

I am getting the suggestion for both youtube and Spotify

**Comment by h45h74x** [comment]
Hi there, I've got the same issue and can offer logs.

**What's happening?**

I'm currently testing the bot on my development machine (started via yarn), but will use it with docker on a Debian server in the future. When executing `/play`, muse answers with "🚫ope: Request failed with status code 403"

**Logs**

Immediate log output in the console, after executing `/play`:




```
Error: type chipCloudRenderer is not known
    at parseItem (/home/sim/Userdata/WDir/muse/node_modules/ytsr/lib/parseItem.js:74:13)
    at catchAndLogFunc (/home/sim/Userdata/WDir/muse/node_modules/ytsr/lib/parseItem.js:81:12)
    at module.exports (/home/sim/Userdata/WDir/muse/node_modules/ytsr/lib/parseItem.js:104:46)
    at /home/sim/Userdata/WDir/muse/node_modules/ytsr/lib/main.js:53:34
    at Array.map (<anonymous>)
    at module.exports (/home/sim/Userdata/WDir/muse/node_modules/ytsr/lib/main.js:53:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async KeyValueCacheProvider.wrap (file:///home/sim/Userdata/WDir/muse/src/services/key-value-cache.ts:46:20)
    at async run (file:///home/sim/Userdata/WDir/muse/node_modules/p-queue/dist/index.js:109:36)

/********************************************************************************************************************************************************************************************************
failed at func parseItem: type chipCloudRenderer is not known
pls post the the files in /home/sim/Userdata/WDir/muse/node_modules/ytsr/dumps to https://github.com/TimeForANinja/node-ytsr/issues
os: linux-x64, node.js: v16.15.0, ytsr: 3.6.0
********************************************************************************************************************************************************************************************************\
```

**Screenshots**
If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/27204033/166114707-99e1fb47-8beb-4c10-8f1b-806ef14a27d8.png)

![image](https://user-images.githubusercontent.com/27204033/166114723-e3827a61-6d4b-4c59-adf9-d0d04b3a2f98.png)

![image](https://user-images.githubusercontent.com/27204033/166114732-a03d57f4-b073-429f-952f-06c29419f048.png)


**Runtime**
I'm running Muse:
- [x] Directly from the cloned repository
- [ ] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: 1.9.0
- Docker (if applicable):
- OS: Arch 5.17.4-zen1-1-zen x86_64
- Node: v16.15.0
- ffmpeg: 2:5.0-6

**Comment by codetheweb** [comment]
Thanks for the detailed report. The bot is currently broken, please follow https://github.com/codetheweb/muse/issues/637 for updates.

**Comment by codetheweb** [comment]
This should be fixed in https://github.com/codetheweb/muse/releases/tag/v2.0.0. Please re-open if you're still having issues.

**Comment by Dazzuh** [comment]
Looks like this is still happening in 2.0.4, pretty much identical to what @h45h74x described, Although I'm running directly from cloned repo on WSL2, Win11. also tried running outside of WSL, same issue.

**Comment by h45h74x** [comment]
I forgot to post my solution here, sorry. I fixed my problem by creating a completely new Project + API key in the Google cloud dashboard (just like @Dazzuh). Whilst the key I used for muse had access to all required APIs, only the new key worked properly.
