### ISSUE TITLE
Bot hosting on local server

### ISSUE THREAD

**Issue by Khaled1066** [codetheweb/muse#555]
Hello,

I have a small local server, and I was wondering how I can host Muse on the server for it to be 24/7  online

**Comment by codetheweb** [comment]
Sorry, not exactly sure what you're asking. If you want to run Muse on a server I would recommend running with Docker Compose (example in README).

**Comment by Khaled1066** [comment]
I meant it have the bot always only even of I turn of my PC
 since i have my own physical server I want to host it there

**Comment by codetheweb** [comment]
Ok, if you have a server I would recommend using Docker Compose.
