### ISSUE TITLE
Enhancement - Queue System

### ISSUE THREAD

**Issue by dotxyzcf** [codetheweb/muse#568]
Let's say I load a playlist with 50 songs (yesterday). Then the bot says now playing (song). If the song is over it would be annoying to write a new message and get a new discord ping through it (good that it doesn't do that). I would find it alternatively good, if the bot edit the old now playing message with the new song. That way you save yourself a re-ping and you can save /queue to find out what the bot is playing. Good idea? Implementable? I hope so. Thanks

**Comment by codetheweb** [comment]
Sorry, not really sure what you're asking. Are you saying the response from `/play` should be continually updated with the current song?

**Comment by dotcf** [comment]
The problem currently is that when you start a song and it is over, there is no new message with now playing. Instead you have to run /queue aslus to list the current song. It would be better if he edits the old now playing message with the new current song.

[![IMG_20220316_065211.jpg](https://user-images.githubusercontent.com/92203938/158525320-6b0b23fd-066f-4ac6-bb21-767a990bfdb7.jpg)

**Comment by codetheweb** [comment]
I looked at this in the past but ultimately decided it didn't make sense to do. See https://github.com/codetheweb/muse/issues/331#issuecomment-1001871013 for context.
