### ISSUE TITLE
Massive YouTube playlists throw error

### ISSUE THREAD

**Issue by dotcf** [codetheweb/muse#573]
![image](https://user-images.githubusercontent.com/92203938/158246297-3bd5270f-140d-4652-a922-7782e2cd1bf0.png)
![image](https://user-images.githubusercontent.com/92203938/158246301-aaa6df88-076a-4f2a-9e19-18d1896fd6d5.png)
![image](https://user-images.githubusercontent.com/92203938/158246302-414ad584-0985-4b9c-a314-2ede4ad7c15e.png)

as you can see here im not able to load playlists from youtube. but spotify works fine. why? is this normal? or is it missing? can someone fix this?

![image](https://user-images.githubusercontent.com/92203938/158246492-51d3ed3d-713b-411c-96f1-fdb8f7d74a82.png)

**Comment by bokherus** [comment]
It does work for smaller playlist e.g. https://www.youtube.com/playlist?list=PL5jPae7A2fkZg3sjG4PvvbfjZBTJ4bgxL
However, when I tried the playlist in your snapshot https://www.youtube.com/playlist?list=PLWwAypAcFRgKAIIFqBr9oy-ZYZnixa_Fj that has `5000 videos` . It throws an error.
```
muse/node_modules/@prisma/client/runtime/index.js:39813
        throw new PrismaClientUnknownRequestError(message, this.client._clientVersion);
              ^

PrismaClientUnknownRequestError: 
Invalid `prisma.keyValueCache.upsert()` invocation:


  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: ConnectionError(Timed out during query execution.) })
    at Object.request (muse/node_modules/@prisma/client/runtime/index.js:39813:15)
    at async PrismaClient._request (muse/node_modules/@prisma/client/runtime/index.js:40637:18)
    at async KeyValueCacheProvider.wrap (file: muse/src/services/key-value-cache.ts:49:5)
    at async file: muse/src/services/youtube-api.ts:95:45 {
  clientVersion: '3.10.0'
}
```

**Comment by dotcf** [comment]
Tested with 660 songs. that worked. but idk when it will be buggy

**Comment by codetheweb** [comment]
Thanks for the report.
