### ISSUE TITLE
Add required minimum versions of prerequisites

### ISSUE THREAD

**Issue by Zagrthos** [codetheweb/muse#579]
Could you add a note in the README which minimum or recommended versions of the prerequisites we should use?

We _can_ certainly use the newest version but for compatibility reasons it would be better if you specify it.
One said in the closed Issues that Node.js 17 does have a few problems with muse and 16.x is more recommended.
Your docker file also uses 16.x so why not add it straight to the README?

**Comment by codetheweb** [comment]
Happy to accept a PR for this. 👍

**Comment by Zagrthos** [comment]
I also added a 24/7 command just in case someone needs it. Saved my nerves a few times while using ssh.. 😄
