### ISSUE TITLE
FFmpeg process kept open for livestreams

### ISSUE THREAD

**Issue by Hellysonrp** [codetheweb/muse#580]
The FFmpeg process is kept open for livestreams, even after skipping it or stopping the playback.

## Steps to reproduce
* Pick a livestream and play it
* Skip it or stop the playback
* Play it again
* Repeat the above as much as you like
* View open processes in the OS

In my case, after playing a livestream twice and stopping the playback, this is what I found in `htop`:
![Screenshot_44](https://user-images.githubusercontent.com/5438762/158715719-71548060-9cdb-4635-af7f-8f8c18d58ea3.png)

This behavior is specially problematic for infinite livestreams, like web radios, since the stream will end only if something goes wrong.
This is an example of a web radio streaming URL: [http://sc8.1.fm:7700/](http://sc8.1.fm:7700/)

## My environment
Linux Debian 11.2 VM running on `xcp-ng`
Muse version 1.6.0

**Comment by codetheweb** [comment]
Thanks for the report!
