### ISSUE TITLE
BUG - Embed Now Playing content not showing on play a new song if bot is already in channel

### ISSUE THREAD

**Issue by dotxyzcf** [codetheweb/muse#581]
![grafik](https://user-images.githubusercontent.com/92203938/158864963-132ed2b7-d041-49ac-b9c1-c3d101dd2fba.png)

As you can see here, the now playing embed content is not showing if the bot is already in the channel and i start a song. if it need to join to play the embed works. is this a bug?

**Comment by codetheweb** [comment]
This is intentional behavior. Adding an embed after adding something to the back of the queue doesn't really make sense because something else is currently playing. 

Note that embeds are created for commands like `/skip` that change the current track.
