### ISSUE TITLE
Enhancement - Now Playing Command

### ISSUE THREAD

**Issue by Zagrthos** [codetheweb/muse#588]
Added a "Now Playing" Command to show the currently played song.
#587 

This was mainly made for my server but eventually you want it too.
I took the one from the first /play Command and made a new Slash Command out of it.

Text in the screenshot is in German but I've changed it in the code to English:
![image](https://user-images.githubusercontent.com/36556009/159043044-fad66361-c8f8-4c53-9e00-64cb7a3bd9f3.png)

**Comment by codetheweb** [comment]
Could you expand on what the use case is for this? `/queue` also shows the currently playing track.

**Comment by Zagrthos** [comment]
A few people in my server requested to see just the currently played song without the others, so I made them an extra command for that and wanted to share this.

Plans for the future were to maybe include an embedded message which refreshes after new songs or it sends a new message when a new song is played but I think someone else requested this first and it was declined.

**Comment by codetheweb** [comment]
Got it, I think it makes sense then. 👍
