### ISSUE TITLE
Problem - Favorites

### ISSUE THREAD

**Issue by dotxyzcf** [codetheweb/muse#606]
What if there are to many favourites to list with /favorites list? As i see there is no page system for that one. So if it would be to many the bot CANT list it

**Comment by dotxyzcf** [comment]
![grafik](https://user-images.githubusercontent.com/92203938/160232318-092e2fba-db72-4fa1-9b9b-0a2d60d440f9.png)
no page argument like in /queue
![grafik](https://user-images.githubusercontent.com/92203938/160232326-e1f008c1-42bf-4c02-8e5d-9cdf4b460b23.png)

**Comment by Zagrthos** [comment]
Can't see a limit of favorites in the building process of the respected Embed. So, I think it will just post all favorites in one Message Embed and because of that there is no need of a page Split.

**Comment by dotxyzcf** [comment]
discord has a charter limit of 2000 charters???

**Comment by dotxyzcf** [comment]
and why there is on queue a page system if there is no charter limit?

**Comment by Zagrthos** [comment]
You could also try if there is a limit and let us know then, would be way easier than speculating. :)

**Comment by dotxyzcf** [comment]
here the proof :)

![image](https://user-images.githubusercontent.com/92203938/160274524-d87deac5-5f6a-4acf-bee2-7e338a31e80f.png)

**Comment by dotxyzcf** [comment]
limited to 4096 charters. so a page system would be a fix as it is in /queue

**Comment by codetheweb** [comment]
Happy to accept a PR to fix this. I think we might be able to get around the limit by making multiple embeds instead of having to create a page system.

**Comment by Codixer** [comment]
Yes and no, if you have multiple embeds the number gets boosted to 6000 characters (4096 max for each embed, 2000 for normal text). However past that you are forced to paginate. Possibly with buttons or another method.
