### ISSUE TITLE
Gettting could not find settings for guild error

### ISSUE THREAD

**Issue by krzysiek-4** [codetheweb/muse#619]
I am trying to run the code for docker :
docker run -it -v "$(pwd)/data":/data -e DISCORD_TOKEN='' -e SPOTIFY_CLIENT_ID='' -e SPOTIFY_CLIENT_SECRET='' -e YOUTUBE_API_KEY='' codetheweb/muse:latest

and i am getting the below
![image](https://user-images.githubusercontent.com/9113596/162626268-a00496c5-2c18-47d7-a1ee-9837866408e8.png)

**Comment by codetheweb** [comment]
This means that Muse is currently part of a server that it doesn't know about in its local database. Did you recently switch what machine you run Muse on and not copy the database? You can also try kicking Muse from all servers and re-inviting.
