### ISSUE TITLE
Bot online, doessn`t recact to commands

### ISSUE THREAD

**Issue by Luemmel-git** [codetheweb/muse#627]
I have installed the Bot with docker-compose on my raspberry pi 3 with raspbian 64bit.
In Discord it shows as online but doesn´t react to any commands. I gave it admin Priviliges but that changed nothing.
the command prefix is not documented anywhere so i tried "." and "/" as seen in the short videos on the blog.

**Comment by codetheweb** [comment]
Is there anything relevant in the logs?

**Comment by Luemmel-git** [comment]
mybe this:
muse_1  | 
muse_1  | D[50001]: Missing Access
muse_1  |     at C.runRequest (file:///usr/app/node_modules/@discordjs/rest/dist/index.mjs:7:557)
muse_1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
muse_1  |     at async C.queueRequest (file:///usr/app/node_modules/@discordjs/rest/dist/index.mjs:5:3022)
muse_1  |     at async file:///usr/app/src/bot.ts:113:13
muse_1  |     at async Promise.all (index 0)
muse_1  |     at async Client.<anonymous> (file:///usr/app/src/bot.ts:111:9) {
muse_1  |   rawError: { message: 'Missing Access', code: 50001 },
muse_1  |   code: 50001,
muse_1  |   status: 403,
muse_1  |   method: 'put',
muse_1  |   url: 'https://discord.com/api/v9/applications/836158248159543318/guilds/622494589412179978/commands',

**Comment by codetheweb** [comment]
It doesn't have permission to create commands. Please kick Muse and re-invite using the invite link in the logs.

**Comment by Luemmel-git** [comment]
wich link, the one in the last line inst a discord invite link and i cant find another

**Comment by codetheweb** [comment]
If you kick Muse and restart the container, it should print an invite link.

**Comment by Luemmel-git** [comment]
i still have an other error now:

muse_1  | - Applying database migrations...
muse_1  | ✔ Database migrations applied.
muse_1  | - 📡 connecting to Discord...
muse_1  | file:///usr/app/src/utils/update-permissions-for-guild.ts:10
muse_1  |     throw new Error("could not find settings for guild");
muse_1  |           ^
muse_1  | 
muse_1  | Error: could not find settings for guild
muse_1  |     at updatePermissionsForGuild (file:///usr/app/src/utils/update-permissions-for-guild.ts:10:11)
muse_1  |     at async Promise.all (index 0)
muse_1  |     at async Client.<anonymous> (file:///usr/app/src/bot.ts:129:7)
muse_1  | file:///usr/app/node_modules/execa/lib/error.js:59
muse_1  |               error = new Error(message);
muse_1  |                       ^
muse_1  | 
muse_1  | Error: Command failed with exit code 1: esmo src/scripts/migrate-and-start.ts
muse_1  |     at makeError (file:///usr/app/node_modules/execa/lib/error.js:59:11)
muse_1  |     at handlePromise (file:///usr/app/node_modules/execa/index.js:119:26)
muse_1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
muse_1  |     at async file:///usr/app/src/scripts/run-with-database-url.ts:5:3 {
muse_1  |   shortMessage: 'Command failed with exit code 1: esmo src/scripts/migrate-and-start.ts',
muse_1  |   command: 'esmo src/scripts/migrate-and-start.ts',
muse_1  |   escapedCommand: 'esmo "src/scripts/migrate-and-start.ts"',
muse_1  |   exitCode: 1,
muse_1  |   signal: undefined,
muse_1  |   signalDescription: undefined,
muse_1  |   stdout: undefined,
muse_1  |   stderr: undefined,
muse_1  |   failed: true,
muse_1  |   timedOut: false,
muse_1  |   isCanceled: false,
muse_1  |   killed: false
muse_1  | }
muse_1  | error Command failed with exit code 1.
muse_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by wangwill** [comment]
Does the bot need specific port to be opened in firewall?

I encountered a problem that the bot seems stucked in "connecting to Discord"

Also, the bot is not showing an invitaion link

Compose built the docker & if I invite the bot through Discord Developer portal, it is showing that the bot is online but not reacting to any command.

Kick bot & restart docker done, no change.

-----------------------------------------

file:///usr/app/src/utils/update-permissions-for-guild.ts:10

    throw new Error("could not find settings for guild");

          ^

Error: could not find settings for guild

    at updatePermissionsForGuild (file:///usr/app/src/utils/update-permissions-for-guild.ts:10:11)

    at async Promise.all (index 0)

    at async Client.<anonymous> (file:///usr/app/src/bot.ts:129:7)

file:///usr/app/node_modules/execa/lib/error.js:59

		error = new Error(message);

		        ^

Error: Command failed with exit code 1: esmo src/scripts/migrate-and-start.ts

    at makeError (file:///usr/app/node_modules/execa/lib/error.js:59:11)

    at handlePromise (file:///usr/app/node_modules/execa/index.js:119:26)

    at processTicksAndRejections (node:internal/process/task_queues:96:5)

    at async file:///usr/app/src/scripts/run-with-database-url.ts:5:3 {

  shortMessage: 'Command failed with exit code 1: esmo src/scripts/migrate-and-start.ts',

  command: 'esmo src/scripts/migrate-and-start.ts',

  escapedCommand: 'esmo "src/scripts/migrate-and-start.ts"',

  exitCode: 1,

  signal: undefined,

  signalDescription: undefined,

  stdout: undefined,

  stderr: undefined,

  failed: true,

  timedOut: false,

  isCanceled: false,

  killed: false

}

error Command failed with exit code 1.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

yarn run v1.22.15

$ npm run env:set-database-url -- esmo src/scripts/migrate-and-start.ts

> muse@1.9.0 env:set-database-url

> esmo src/scripts/run-with-database-url.ts "esmo" "src/scripts/migrate-and-start.ts"

(node:51) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time

(Use `node --trace-warnings ...` to show where the warning was created)

(node:51) DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: getFormat, transformSource

(node:85) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time

(Use `node --trace-warnings ...` to show where the warning was created)

(node:85) DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: getFormat, transformSource

========================================

========================================

================= muse =================

========================================

=========== Made with 🎶 by ============

==== https://github.com/codetheweb =====

========================================

========================================

Running version 1.9.0 built on Invalid Date (commit unknown)

🔧 Need help? https://github.com/codetheweb/muse/discussions/new

🐛 Bug? https://github.com/codetheweb/muse/issues/new

✨ New feature? https://github.com/codetheweb/muse/issues/new

☕ Discussion? https://github.com/codetheweb/muse/discussions/new

💰 Help me? https://www.paypal.me/codetheweb https://github.com/sponsors/codetheweb

- Applying database migrations...

✔ Database migrations applied.

- 📡 connecting to Discord...
