### ISSUE TITLE
Silence when playing a song

### ISSUE THREAD

**Issue by thecharlie654** [codetheweb/muse#628]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/49923828/164338522-e496e76b-62b6-4026-9b38-bed362fa338e.gif)

When trying to play a song, the voice activity circle briefly flashes but nothing is played - the bot leaves the channel after about 15 seconds. 

FFmpeg is version 5.0.1 and it's running on Oracle Cloud:
![image](https://user-images.githubusercontent.com/49923828/164338718-2a8264cc-314f-475e-abef-fcfc68f7d124.png)

**Comment by codetheweb** [comment]
Is there anything useful in the logs?

**Comment by thecharlie654** [comment]
Nothing is printed in the console normally, with debug on I get this:
`  prisma:client Prisma Client call: +9s
  prisma:client prisma.keyValueCache.findUnique({
  prisma:client   where: {
  prisma:client     key: 'autocomplete:n'
  prisma:client   }
  prisma:client }) +0ms
  prisma:client Generated request: +1ms
  prisma:client query {
  prisma:client   findUniqueKeyValueCache(where: {
  prisma:client     key: "autocomplete:n"
  prisma:client   }) {
  prisma:client     key
  prisma:client     value
  prisma:client     expiresAt
  prisma:client     createdAt
  prisma:client     updatedAt
  prisma:client   }
  prisma:client }
  prisma:client  +0ms
  prisma:client:libraryEngine sending request, this.libraryStarted: true +9s
  muse Cache hit: autocomplete:n +9s
  prisma:client Prisma Client call: +1s
  prisma:client prisma.keyValueCache.findUnique({
  prisma:client   where: {
  prisma:client     key: 'autocomplete:never'
  prisma:client   }
  prisma:client }) +1ms
  prisma:client Generated request: +0ms
  prisma:client query {
  prisma:client   findUniqueKeyValueCache(where: {
  prisma:client     key: "autocomplete:never"
  prisma:client   }) {
  prisma:client     key
  prisma:client     value
  prisma:client     expiresAt
  prisma:client     createdAt
  prisma:client     updatedAt
  prisma:client   }
  prisma:client }
  prisma:client  +0ms
  prisma:client:libraryEngine sending request, this.libraryStarted: true +1s
  muse Cache hit: autocomplete:never +1s
  prisma:client Prisma Client call: +2s
  prisma:client prisma.setting.findUnique({
  prisma:client   where: {
  prisma:client     guildId: '834530407985709067'
  prisma:client   }
  prisma:client }) +1ms
  prisma:client Generated request: +0ms
  prisma:client query {
  prisma:client   findUniqueSetting(where: {
  prisma:client     guildId: "834530407985709067"
  prisma:client   }) {
  prisma:client     guildId
  prisma:client     invitedByUserId
  prisma:client     playlistLimit
  prisma:client     secondsToWaitAfterQueueEmpties
  prisma:client     leaveIfNoListeners
  prisma:client     roleId
  prisma:client     createdAt
  prisma:client     updatedAt
  prisma:client   }
  prisma:client }
  prisma:client  +0ms
  prisma:client:libraryEngine sending request, this.libraryStarted: true +2s
  prisma:client Prisma Client call: +285ms
  prisma:client prisma.keyValueCache.findUnique({
  prisma:client   where: {
  prisma:client     key: '["never gonna give you up",{"limit":10}]'
  prisma:client   }
  prisma:client }) +0ms
  prisma:client Generated request: +1ms
  prisma:client query {
  prisma:client   findUniqueKeyValueCache(where: {
  prisma:client     key: "[\"never gonna give you up\",{\"limit\":10}]"
  prisma:client   }) {
  prisma:client     key
  prisma:client     value
  prisma:client     expiresAt
  prisma:client     createdAt
  prisma:client     updatedAt
  prisma:client   }
  prisma:client }
  prisma:client  +0ms
  prisma:client:libraryEngine sending request, this.libraryStarted: true +285ms
  muse Cache hit: ["never gonna give you up",{"limit":10}] +3s
  prisma:client Prisma Client call: +2ms
  prisma:client prisma.keyValueCache.findUnique({
  prisma:client   where: {
  prisma:client     key: '["dQw4w9WgXcQ"]'
  prisma:client   }
  prisma:client }) +1ms
  prisma:client Generated request: +0ms
  prisma:client query {
  prisma:client   findUniqueKeyValueCache(where: {
  prisma:client     key: "[\"dQw4w9WgXcQ\"]"
  prisma:client   }) {
  prisma:client     key
  prisma:client     value
  prisma:client     expiresAt
  prisma:client     createdAt
  prisma:client     updatedAt
  prisma:client   }
  prisma:client }
  prisma:client  +0ms
  prisma:client:libraryEngine sending request, this.libraryStarted: true +3ms
  muse Cache hit: ["dQw4w9WgXcQ"] +7ms
  prisma:client Prisma Client call: +9ms
  prisma:client prisma.fileCache.findUnique({
  prisma:client   where: {
  prisma:client     hash: 'afd225007a8561b11ff551d42cd062fead6b66e44d920fc0b2f6a45c37871fce1b7539264a0409f3076aa27ecffb54de11d2466a86c939714632e50c9d55c7ae'
  prisma:client   }
  prisma:client }) +0ms
  prisma:client Generated request: +1ms
  prisma:client query {
  prisma:client   findUniqueFileCache(where: {
  prisma:client     hash: "afd225007a8561b11ff551d42cd062fead6b66e44d920fc0b2f6a45c37871fce1b7539264a0409f3076aa27ecffb54de11d2466a86c939714632e50c9d55c7ae"
  prisma:client   }) {
  prisma:client     hash
  prisma:client     bytes
  prisma:client     accessedAt
  prisma:client     createdAt
  prisma:client     updatedAt
  prisma:client   }
  prisma:client }
  prisma:client  +0ms
  prisma:client:libraryEngine sending request, this.libraryStarted: true +11ms
  muse [VOICE] received voice state update: {"member":{"user":{"username":"chol's musicbot","id":"880156190221410354","discriminator":"0973","bot":true,"avatar":"26d57316422bed94f0509a0bfd83e75c"},"roles":["966471566227554337"],"premium_since":null,"pending":false,"nick":null,"mute":false,"joined_at":"2022-04-20T22:52:57.649780+00:00","hoisted_role":null,"flags":1,"deaf":false,"communication_disabled_until":null,"avatar":null},"user_id":"880156190221410354","suppress":false,"session_id":"6c1107893f29d9b5f83f30d53c53f46e","self_video":false,"self_mute":false,"self_deaf":true,"request_to_speak_timestamp":null,"mute":false,"guild_id":"834530407985709067","deaf":false,"channel_id":"834530408493613131"} +106ms
  prisma:client Prisma Client call: +102ms
  prisma:client prisma.setting.findUnique({
  prisma:client   where: {
  prisma:client     guildId: '834530407985709067'
  prisma:client   }
  prisma:client }) +1ms
  prisma:client Generated request: +0ms
  prisma:client query {
  prisma:client   findUniqueSetting(where: {
  prisma:client     guildId: "834530407985709067"
  prisma:client   }) {
  prisma:client     guildId
  prisma:client     invitedByUserId
  prisma:client     playlistLimit
  prisma:client     secondsToWaitAfterQueueEmpties
  prisma:client     leaveIfNoListeners
  prisma:client     roleId
  prisma:client     createdAt
  prisma:client     updatedAt
  prisma:client   }
  prisma:client }
  prisma:client  +1ms
  prisma:client:libraryEngine sending request, this.libraryStarted: true +105ms
  muse [VOICE] received voice server: {"t":"VOICE_SERVER_UPDATE","s":9,"op":0,"d":{"token":"77bf70dd0904d618","guild_id":"834530407985709067","endpoint":"rotterdam1815.discord.media:443"}} +94ms
  muse Spawned ffmpeg with ffmpeg -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5 -to 213 -i https://rr4---sn-aigzrn7e.googlevideo.com/videoplayback?expire=1650517937&ei=UZNgYuiEEM-l1waimZ6ABw&ip=132.145.17.43&id=o-AAgC5fSoeS6qetlrS7YCZk_YNWTH4CL_3iUiNiWNWDVq&itag=251&source=youtube&requiressl=yes&mh=7c&mm=31%2C29&mn=sn-aigzrn7e%2Csn-aigl6ner&ms=au%2Crdu&mv=m&mvi=4&pl=26&initcwndbps=2053750&spc=4ocVC3iFXAAEZx-pXpmFXh4bxHXH&vprv=1&mime=audio%2Fwebm&ns=SYGzWZGdWM3Ow2lQj3tl4ooG&gir=yes&clen=3437753&dur=212.061&lmt=1644662749424319&mt=1650496146&fvip=4&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=4532434&n=jGqBbdIf2SBspQ&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgDSS0EhVX4joO4XfPC7G2OdI8pyohygMIK926dRsALuACIGUf_UWSZ9Hj7e_6JLsJ8vinfJbBSa1ie4P3QV637GBs&sig=AOq0QJ8wRAIgbwg8v6XPWANQZiVV0QhA-7VfGiCmbJ6PnFeGhNTOq-ACIAmUnFvUCTrIpooLdarXqKlzeYeolktg0Nfiy5rN-qCb -acodec libopus -vn -f webm pipe:1 +955ms
  prisma:client Prisma Client call: +1s
  prisma:client prisma.setting.findUnique({
  prisma:client   where: {
  prisma:client     guildId: '834530407985709067'
  prisma:client   }
  prisma:client }) +1ms
  prisma:client Generated request: +1ms
  prisma:client query {
  prisma:client   findUniqueSetting(where: {
  prisma:client     guildId: "834530407985709067"
  prisma:client   }) {
  prisma:client     guildId
  prisma:client     invitedByUserId
  prisma:client     playlistLimit
  prisma:client     secondsToWaitAfterQueueEmpties
  prisma:client     leaveIfNoListeners
  prisma:client     roleId
  prisma:client     createdAt
  prisma:client     updatedAt
  prisma:client   }
  prisma:client }
  prisma:client  +0ms
  prisma:client:libraryEngine sending request, this.libraryStarted: true +1s
  muse [WS => Shard 0] [HeartbeatTimer] Sending a heartbeat. +27s
  muse [WS => Shard 0] Heartbeat acknowledged, latency of 92ms. +92ms
  muse [VOICE] received voice state update: {"member":{"user":{"username":"chol's musicbot","id":"880156190221410354","discriminator":"0973","bot":true,"avatar":"26d57316422bed94f0509a0bfd83e75c"},"roles":["966471566227554337"],"premium_since":null,"pending":false,"nick":null,"mute":false,"joined_at":"2022-04-20T22:52:57.649780+00:00","hoisted_role":null,"flags":1,"deaf":false,"communication_disabled_until":null,"avatar":null},"user_id":"880156190221410354","suppress":false,"session_id":"6c1107893f29d9b5f83f30d53c53f46e","self_video":false,"self_mute":false,"self_deaf":true,"request_to_speak_timestamp":null,"mute":false,"guild_id":"834530407985709067","deaf":false,"channel_id":null} +4s
  muse [WS => Shard 0] [HeartbeatTimer] Sending a heartbeat. +38s
  muse [WS => Shard 0] Heartbeat acknowledged, latency of 92ms. +92ms`

**Comment by codetheweb** [comment]
I don't think this is the issue, but would it be possible to quickly install ffmpeg 4.1 and see if that works?

In general, I would recommend running Muse in a container if at all possible.

**Comment by thecharlie654** [comment]
Yeah same issue with ffmpeg 4.1

**Comment by codetheweb** [comment]
Have you tried multiple different YouTube videos?

**Comment by STK0Cervanthes** [comment]
> Have you tried multiple different YouTube videos?

Hey there, 

i went ahead and tried multiple videos as well as spotify links and plain text search everything without success in getting audio

**Comment by codetheweb** [comment]
Hmm, not sure what else could be the issue.

Could you try running Muse as a container?

**Comment by STK0Cervanthes** [comment]
> Hmm, not sure what else could be the issue.
> 
> Could you try running Muse as a container?

Throwing it Into a container solved that issue ^^ 

I tried a bit around after that and set the bot up from the beginning again and installed ffmpeg 5.0.1 like OP and it actually worked out 

Might have been a temporary issue? Not sure
