### ISSUE TITLE
Loop

### ISSUE THREAD

**Issue by Luemmel-git** [codetheweb/muse#630]
Is it possible to add a loop feature to restart the queue after finishing?

**Comment by codetheweb** [comment]
Could you explain how this would work?

**Comment by Luemmel-git** [comment]
You have a queue of like 10 Songs and type / loop. If the last song of the queue is finished it starts at the first again

**Comment by Luemmel-git** [comment]
Technicaly just add every song to the end of the queue again after it finished

Maybe let /loop toggle that behavior or just add a /loop true and /loop false

**Comment by Zagrthos** [comment]
I think there's already an issue present with the same request. #524

**Comment by Luemmel-git** [comment]
Ah sorry, didnt see
