### ISSUE TITLE
Docker installation error: Failed to apply database migrations:

### ISSUE THREAD

**Issue by akamuraaa** [codetheweb/muse#632]
hi, i haven't worked with yarn, npm, etc.
can you pls help me :)

**Screenshots**
![image](https://user-images.githubusercontent.com/104314814/164984373-4c324b30-d55e-4aab-bdb3-bc45b83e27a4.png)

**Versions**
- Docker (if applicable): Docker version 20.10.12, build 485636f
- OS: Fedora Server 5.16.20-200.fc35.x86_64

**Comment by codetheweb** [comment]
The issue is what it says. It can't open the database file location. 

What does your Docker Compose file look like? (Or the Docker command you used, if you're not using Compose.)

**Comment by akamuraaa** [comment]
I used the command you proved in the "Running" Section.
docker run -it -v "$(pwd)/data":/data -e DISCORD_TOKEN='' -e SPOTIFY_CLIENT_ID='' -e SPOTIFY_CLIENT_SECRET='' -e YOUTUBE_API_KEY='' codetheweb/muse:latest
(yes i didn't forget to fill in the empty spaces)

**Comment by akamuraaa** [comment]
I also tryed the node.js installation, but same error

**Comment by codetheweb** [comment]
You probably don't have permission to write files in the current directory. Try changing `-v "$(pwd)/data" to a new folder in your home directory or something.

**Comment by akamuraaa** [comment]
i'm root, so i have the permission in my root directory.
this is my yarn-error.log
![image](https://user-images.githubusercontent.com/104314814/165096850-e6ff3f33-b873-4c5e-a676-2136350af268.png)

**Comment by akamuraaa** [comment]
i got a new error. i tryed it again with the nodejs installation and the npm commands.
![image](https://user-images.githubusercontent.com/104314814/165099767-af064b57-e409-4b8c-9bdf-3d29ba191b5c.png)

**Comment by slidez1337** [comment]
I get the same error

**Comment by codetheweb** [comment]
Please double-check that you copied the token (without spaces) correctly from Discord.

**Comment by slidez1337** [comment]
the bot is going online but just for a couple of seconds and then offline again, so I guess the token is correct? still same issue

**Comment by codetheweb** [comment]
Bot is currently broken, please follow https://github.com/codetheweb/muse/issues/637 for updates.
