### ISSUE TITLE
could not find settings for guild

### ISSUE THREAD

**Issue by Jindego** [codetheweb/muse#644]
Running version 1.9.0 built on 4/23/2022 (commit 1ef05aba9d2e692ef365721f725be2d2a4e464d9)

🔧 Need help? https://github.com/codetheweb/muse/discussions/new
🐛 Bug? https://github.com/codetheweb/muse/issues/new
✨ New feature? https://github.com/codetheweb/muse/issues/new
☕ Discussion? https://github.com/codetheweb/muse/discussions/new
💰 Help me? https://www.paypal.me/codetheweb https://github.com/sponsors/codetheweb

✔ Database migrations applied.
⠹ 📡 updating commands in all guilds...file:///usr/app/src/utils/update-permissions-for-guild.ts:10
    throw new Error("could not find settings for guild");
          ^

Error: could not find settings for guild
    at updatePermissionsForGuild (file:///usr/app/src/utils/update-permissions-for-guild.ts:10:11)
    at async Promise.all (index 0)
    at async Client.<anonymous> (file:///usr/app/src/bot.ts:129:7)
file:///usr/app/node_modules/execa/lib/error.js:59
		error = new Error(message);
		        ^

Error: Command failed with exit code 1: esmo src/scripts/migrate-and-start.ts
    at makeError (file:///usr/app/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///usr/app/node_modules/execa/index.js:119:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///usr/app/src/scripts/run-with-database-url.ts:5:3 {
  shortMessage: 'Command failed with exit code 1: esmo src/scripts/migrate-and-start.ts',
  command: 'esmo src/scripts/migrate-and-start.ts',
  escapedCommand: 'esmo "src/scripts/migrate-and-start.ts"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
npm notice
npm notice New minor version of npm available! 8.1.0 -> 8.9.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.9.0
npm notice Run npm install -g npm@8.9.0 to update!
npm notice
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by codetheweb** [comment]
The bot is currently broken. There's a fix in this PR for your issue: https://github.com/codetheweb/muse/pull/640.

Please follow that for updates.
