### ISSUE TITLE
invitedByUserId column missing

### ISSUE THREAD

**Issue by hubret** [codetheweb/muse#655]
**What's happening?**
After upgrading to 2.0.1 (from 1.9.0) I get the error in the first screenshot. I added the column manually into the database, and then I got the second error.

Also, I can't replicate it, but there was also an error in the console trying to access the same column, but with `prisma.setting.upsert()`. I'm assuming that this is the first-run behaviour to set the id of the user who invites the bot.

**Logs**

n/a

**Screenshots**
![image](https://user-images.githubusercontent.com/8590448/168424330-470dc244-b6c4-430a-bf04-051ed9a80d28.png)
![image](https://user-images.githubusercontent.com/8590448/168424913-123fd76a-f4f3-44ec-92ed-94f9b60021f3.png)

**Runtime**
I'm running Muse:
- [x] Directly from the cloned repository
- [ ] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: 2.0.1
- Docker (if applicable):
- OS: ubuntu 18

**Comment by codetheweb** [comment]
Depending on how you're running it you may need to re-generate the Prisma client with `yarn prisma generate`.

There are no longer any references to `invitedByUserId` in the code, so feel free to remove it from your database again.
