### ISSUE TITLE
Guild error in Discord. Bot is starting normaly.

### ISSUE THREAD

**Issue by akamuraaa** [codetheweb/muse#656]
**What's happening?**
Bot is starting, but i get a error message in Discord.

**Screenshots**
![image](https://user-images.githubusercontent.com/104314814/168442139-c7c06f29-8f0f-448f-8308-793455968c9a.png)
![image](https://user-images.githubusercontent.com/104314814/168442160-b4397967-b827-4926-8a4e-02feb0a4facc.png)

**Additional context**
I used all tokens in generated before the v2 update. 
Also i didn't worked before the update. So it never worked for me before.

**Runtime**
I'm running Muse:
- [x ] Directly from the cloned repository
- [ ] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: 2.0.2
- OS: Fedora Server 5.17.5-200.fc35.x86_64

**Comment by codetheweb** [comment]
Please try kicking Muse from your guild and re-adding.

**Comment by akamuraaa** [comment]
Worked. Thanks

**Comment by samrudd** [comment]
When adding to a second server it doesn’t work for me

**Comment by samrudd** [comment]
Do I need to add the guild ID in config?

**Comment by codetheweb** [comment]
@samrudd your issue sounds unrelated, please open a new issue with additional details.
