### ISSUE TITLE
Not starting up on my server

### ISSUE THREAD

**Issue by piotr25691** [codetheweb/muse#733]
**What's happening?**
The bot used to start up, however it doesn't anymore. All the tokens are still valid

**Logs**

```js
> muse@2.1.0 start
npm run env:set-database-url -- esmo src/scripts/migrate-and-start.ts

> muse@2.1.0 env:set-database-url
> esmo src/scripts/run-with-database-url.ts
(node:446435) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
node:internal/errors:477
     ErrorCaptureStackTrace(err);
     ^
Error [ERR_LOADER_CHAIN_INCOMPLETE]: "file:///root/runner/private/lh-music/node_modules/esbuild-node-loader/loader.mjs 'resolve'" did not call the next hook in its chain and did not explicitly signal a short circuit. If this is intentional, include `shortCircuit: true` in the hook's return.
    at new NodeError (node:internal/errors:387:5)
    at ESMLoader.resolve (node:internal/modules/esm/loader:860:13 
    at async ESMLoader.getModuleJob (node:internal/modules/esm/loader:439:7)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:541:24)
    at async loadESM (node:internal/process/esm_loader:83:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12) {
    code: 'ERR_LOADER_CHAIN_INCOMPLETE'
}
```

**Screenshots**

**Additional context**

**Runtime**
I'm running Muse:
- [X] Directly from the cloned repository
- [ ] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: 2.1.0 (the same issue occurs on 2.1.1 as well)
- Docker (if applicable):
- OS: Arch Linux
- ffmpeg: (if running outside the Docker container, 4.1 or later is required) 5.0.1

**Comment by codetheweb** [comment]
It looks like `node_modules` might have become corrupted. Try deleting it and re-installing dependencies.

What version of Node.js are you on?

**Comment by piotr25691** [comment]
> It looks like `node_modules` might have become corrupted. Try deleting it and re-installing dependencies.
> 
> What version of Node.js are you on?

It's Node v18.6.0.
I'll try reinstalling the deps.

**Comment by chitinlink** [comment]
Having this same issue in v2.1.3, also running directly from the cloned repo.

**Comment by codetheweb** [comment]
Maybe try Node v16? (I haven't tried v18, although I don't see why that would be a problem.)

**Comment by chitinlink** [comment]
> Maybe try Node v16? (I haven't tried v18, although I don't see why that would be a problem.)

Switched to Node v16.16.0 and it works fine. No idea what in 18 would be doing this but it doesn't matter

**Comment by Sir-Million** [comment]
I am currently having the same problem, I switched to node 16 and it still doesn't work

```
Error [ERR_LOADER_CHAIN_INCOMPLETE]: "file:///app/node_modules/esbuild-node-loader/loader.mjs 'resolve'" did not call the next hook in its chain and did not explicitly signal a short circuit. If this is intentional, include `shortCircuit: true` in the hook's return.
    at new NodeError (node:internal/errors:387:5)
    at ESMLoader.resolve (node:internal/modules/esm/loader:852:13)
    at async ESMLoader.getModuleJob (node:internal/modules/esm/loader:431:7)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12) {
  code: 'ERR_LOADER_CHAIN_INCOMPLETE'
  }
```

**Comment by chitinlink** [comment]
Just as a sanity check:

* Check `node -v`
* Delete `node_modules` and run `npm i`

**Comment by Sir-Million** [comment]
I just did it, it didn't work
![image](https://user-images.githubusercontent.com/73513663/185717838-d292f3f2-cb3c-4635-a244-4a7e0379617d.png)
![image](https://user-images.githubusercontent.com/73513663/185717890-3498b01a-7e7f-423d-b25a-7142f417f93a.png)
![image](https://user-images.githubusercontent.com/73513663/185717937-92f393ef-8b6f-4746-9f38-69ea1125c27a.png)

**Comment by chitinlink** [comment]
Shrug, I think I also recloned the repo when I got mine to work, but I really don't know

**Comment by Sir-Million** [comment]
strange, I recloned it just before sending the message, just to check if it was a file corruption problem

ps: it wasn't

**Comment by codetheweb** [comment]
I was able to reproduce the issue and it should now be fixed in the above release.
