### ISSUE TITLE
Update documentation regarding `/tmp` ?

### ISSUE THREAD

**Issue by nullstalgia** [codetheweb/muse#752]
**What's happening?**
My docker.img kept filling up due the `/data` path link not being enough for the `/tmp` directory to be synced.

**Screenshots**

Before adding `/tmp` -> `/mnt/disk1/appdata/muse/data/cache/tmp`

![image](https://user-images.githubusercontent.com/20761757/182744038-717e4fb5-a5e0-48ce-bd14-bd619749e7f8.png)

![image](https://user-images.githubusercontent.com/20761757/182744118-feca2143-46c5-4f56-8221-2ced08ce63bb.png)

As you can see, the cache and tmp folders *are* made, but are just empty.

After adding `/tmp` -> `/mnt/disk1/appdata/muse/data/cache/tmp`

![image](https://user-images.githubusercontent.com/20761757/182744171-8446018f-c4f1-440c-ac8b-ed7d4c62bcdc.png)

![image](https://user-images.githubusercontent.com/20761757/182744212-24c48008-d730-4d4a-8965-acea66410791.png)

**Runtime**
I'm running Muse:
- [X] Directly from the cloned repository
- [X] Inside a Docker container
- [X] Something else (unRAID)

**Versions**
- Muse: v2.1.1
- Docker (if applicable): 20.10.5
- OS: unRAID 6.9.2

**Comment by codetheweb** [comment]
I'm pretty confused what's going on here... it looks like other tools (Yarn and Node) are using the same cache directory as Muse, which is very strange. This is what my cache folder looks like:
![Screen Shot 2022-08-04 at 10 06 09 PM](https://user-images.githubusercontent.com/7410405/182992982-fbaab19f-9afc-4321-9c61-d72c6053dc32.png)

Can you take a screenshot of the full config for the Muse container?

**Comment by nullstalgia** [comment]
![image](https://user-images.githubusercontent.com/20761757/183034936-081c9c65-dcfb-4c15-bdf8-55b6063fa0bd.png)

It's entirely possible that I goofed something. Let me know if so.

**Comment by codetheweb** [comment]
Sorry, I'm not super familiar with Unraid. To me everything looks good; with that configuration cache files for Muse will be stored in `/mnt/disk1/appdata/muse/data/cache`. Muse does not store anything in `/tmp`.

**Comment by nullstalgia** [comment]
> Muse does not store anything in /tmp

Just to make sure for my sake:

The temp files (i.e. downloaded music files) are supposed to be in /data/cache/tmp, yeah?

I thought that's what the capacitor files were, but now I'm not certain.

**Comment by codetheweb** [comment]
Relative to the default container config cached files should be `/data/cache`.

The `/tmp` directory in the container is apparently used for other tools, but is not referenced by Muse.

**Comment by nullstalgia** [comment]
After removing the `/tmp` volume mapping and playing some songs. (Only volume mapping is `/data`)

Console in the container:
![image](https://user-images.githubusercontent.com/20761757/183243892-e468c744-d6c5-4348-9abc-af41e8fc4a39.png)

Console of the host:
![image](https://user-images.githubusercontent.com/20761757/183243929-02a29aa9-8255-4418-9feb-d8622a100ed7.png)

**Comment by codetheweb** [comment]
Just tried this and found a bug. 😅

I think https://github.com/codetheweb/muse/pull/767 should fix your issue.
