### ISSUE TITLE
Invalid regular expression: missing /

### ISSUE THREAD

**Issue by unixbird** [codetheweb/muse#774]
**What's happening?**
When trying to do a normal /play query: whatever command the bot joins and then the message "ope: Invalid regular expression: missing /" pops up. The bot will then stay for 30 seconds and then leave. No crash messages are present

Message #music

**Logs**
Looking at docker logs gives normal startup and last message is the discord invite link.

**Screenshots**

**Additional context**

**Runtime**
I'm running Muse:
Docker

**Versions**
- Muse: Latest
- Docker (if applicable): 20.10.17
- OS: Ubuntu 20.04

**Comment by sypion** [comment]
Here's a screenshot too if necessary:
![image](https://user-images.githubusercontent.com/8906653/185296164-c301f43c-c7ec-4917-b5de-f6612f1fe9d5.png)

**Comment by Dumdidldum** [comment]
facing the same issue here

**Comment by cvgore** [comment]
Might be related
https://discord.com/developers/docs/change-log#add-subcommand-groups-and-subcommands-to-message-interaction-objects

**Comment by Maikel1990** [comment]
Also having the same issue

**Comment by Midefos** [comment]
Hello, I am having the same issue here:
![imagen](https://user-images.githubusercontent.com/20586481/185489796-ce75bc9a-6c3a-40cc-b827-935e3c017e16.png)
Searching by text in the /play command works well, but when playing something, it appears.

**Comment by gecko10000** [comment]
The full error looks like this (I added `console.log(error)` [here](https://github.com/codetheweb/muse/blob/master/src/utils/error-msg.ts#L8)):
```
evalmachine.<anonymous>:11
"mfZru","cfYAzm",1897615910,414154674,"IluoVc5",null,1,"XsmT",-659785013,577478260,-419211961,1087899650,/,,[/,913,/](,)};Wka(ncode);
                                                                                                         ^

SyntaxError: Invalid regular expression: missing /
    at new Script (node:vm:101:7)
    at exports.decipherFormats (/home/workspace/muse-eternals/node_modules/ytdl-core/lib/sig.js:116:51)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async exports.getInfo (/home/workspace/muse-eternals/node_modules/ytdl-core/lib/info.js:401:17)
```

**Comment by xMikux** [comment]
Look like it is from ytdl-core issue: https://github.com/fent/node-ytdl-core/issues/1110

There has temporary fix, and I try to change the package.json, build again, and it back to work normally.
https://github.com/fent/node-ytdl-core/issues/1110#issuecomment-1219856316

**Comment by codetheweb** [comment]
I tried downgrading `ytdl-core` to 4.10.0 and it still didn't work for me. If someone lets me know when the issue is resolved on `ytdl-core` I can bump the version here as needed (PRs are also great :)).

**Comment by brianterry-ama** [comment]
Switching to the suggested branch for fixed it for me
`npm i ytdl-core@https://github.com/GreepTheSheep/node-ytdl-core`

**Comment by xMikux** [comment]
Maybe we can build the one temporary fix image for now, until they merge the fix.

**Comment by unixbird** [comment]
So it looks like the docker image was updated. The error is still the same but has changed itself to say "Missing catch or finally after try"

**Comment by xMikux** [comment]
yeah, repo author tries to downgrade ytdl-core, but it doesn't fix.

**Comment by xMikux** [comment]
I will build the temporary fix image later, until ytdl-core merge the fix pr, and bump up version.

**Comment by xMikux** [comment]
Okay done.

Image:
``ghcr.io/xmikux/muse:fix``

Commit and action:
https://github.com/xMikux/muse/commit/1bf9f4645e75497520f77405f1f320525e968e09

**Comment by xMikux** [comment]
It looks like this issue has been fixed.

**Comment by davidchalifoux** [comment]
@codetheweb Hey, I just pulled the `latest` docker image and got this error. Should the latest be fixed?

**Comment by mysticpoisen** [comment]
I've also been seeing this with both latest, 2.1.6, and xMikux's fix package. Was working fine yesterday.

**Comment by unixbird** [comment]
I remember reading how youtube was doing some things to make ytdl less easy to use. But this is happening to me as well again.

**Comment by codetheweb** [comment]
https://github.com/fent/node-ytdl-core/issues/1131

**Comment by xMikux** [comment]
Another temporary fix https://github.com/fent/node-ytdl-core/issues/1131#issuecomment-1234232869

I will build fix image again, but not sure what will cause actually (I using sed command to replace string)
but it look like can normally play music.

**Comment by xMikux** [comment]
Okay another done.

Image (will delete when this issue fix):
``ghcr.io/xmikux/muse:fix``

Commit and action:
https://github.com/xMikux/muse/commit/e58ec0267680e8dfc8577bae46f3afdd1b78ce94

**Comment by mysticpoisen** [comment]
Confirming @xMikux's fix package is working(and giving me nice english text too)

**Comment by xMikux** [comment]
Well, I just give up my weird english.

And I see there have a new release ytdl-core v4.11.2 fix this again.

Hope google won't break this again.
