### ISSUE TITLE
how do I change default bot volume?

### ISSUE THREAD

**Issue by QuantumRage100** [codetheweb/muse#785]
I tried having a look but I cant see a way to change the default bot volume, I see can see a line that says "volumes:" in the readme file, but theirs no documentation or config files that I can see to let me set the volume

**Comment by codetheweb** [comment]
`volumes` in the readme is a config value for Docker Compose, not Muse.

See https://github.com/codetheweb/muse/issues/360 (still willing to accept a PR).

**Comment by QuantumRage100** [comment]
I'm not running the bot with docker, is their a way to change the default volume when just, running on windows in cmd?

**Comment by codetheweb** [comment]
There's no way currently to change the default volume.
