### ISSUE TITLE
Error when starting the bot on Linux.

### ISSUE THREAD

**Issue by Lolo280374** [codetheweb/muse#786]
**What's happening?**
When running npm run start to start the bot, everything works fine till an error pops up. I can't do anything, even after doing sudo -i and sudo -l, nothing works. I also tried sudo npm run start

**Logs**
```
xxxxxxxxx@lolos-gcp-vm:/home/XXX/zentaro-files-main$ npm run start

> muse@2.1.4 start
> npm run env:set-database-url -- tsx src/scripts/migrate-and-start.ts


> muse@2.1.4 env:set-database-url
> tsx src/scripts/run-with-database-url.ts

/tmp/envset-database-url-e954067b.sh: 1: tsx: Permission denied
```

**Screenshots**
If applicable, add screenshots to help explain your problem. (None to provide)

**Additional context**
This happens every time i try to run sudo npm run start or npm run start.

**Runtime**
I'm running Muse:
- [X] Directly from the cloned repository
- [ ] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: 2.1.4
- Docker (if applicable): not applicable
- OS: Ubuntu 20.04.4 LTS x86_64
- Node.js: v16 LTS
- ffmpeg: ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers

**Comment by codetheweb** [comment]
How did you install the dependencies?

**Comment by Lolo280374** [comment]
I installed the depedencies using `sudo npm i` in the bot folder. After doing that, no problems occurs. Tho, still can't start the bot.

**Comment by Lolo280374** [comment]
fixed the issue by recloning the repo
