### ISSUE TITLE
🚫ope: Can't cut unsupported JSON (no matching closing bracket found)

### ISSUE THREAD

**Issue by annotated-driftwood** [codetheweb/muse#799]
Bot was working all morning, no changes were made to docker container, docker-compose file, or server settings. Suddenly started refusing to play anything and returning 🚫ope: Can't cut unsupported JSON (no matching closing bracket found) for all queries.

v2.1.6
docker container managed by docker-compose
ubuntu 20.04 VM, 4GB RAM 8 Cores

**Comment by PhoenixSheppy** [comment]
Having exact same issue. Very strange...

**Comment by mrnate72** [comment]
> Bot was working all morning, no changes were made to docker container, docker-compose file, or server settings. Suddenly started refusing to play anything and returning 🚫ope: Can't cut unsupported JSON (no matching closing bracket found) for all queries.
> 
> v2.1.6 docker container managed by docker-compose ubuntu 20.04 VM, 4GB RAM 8 Cores


I also had this issue. I shut down the bot, deleted node_modules and did 'npm i' again and that fixed it for me.
Not sure if that is the fix, but it worked for me

**Comment by annotated-driftwood** [comment]
> I also had this issue. I shut down the bot, deleted node_modules and did 'npm i' again and that fixed it for me. Not sure if that is the fix, but it worked for me

Since I am running in a docker container, this will take some doing. If I can make it work, I will post steps here.

**Comment by codetheweb** [comment]
Please pull the latest release, this should be fixed.
