### ISSUE TITLE
Issue with longer "songs" (1h+)

### ISSUE THREAD

**Issue by ModernChaot** [codetheweb/muse#801]
**What's happening?**
Concisely describe what's going wrong.

The issue is that I try to play this song alone with the playlist it involved: https://www.youtube.com/watch?v=n61ULEU7CO0&list=PL6NdkXsPL07KN01gH2vucrHCEyyNmVEx4

Muse will continue playing but stop about a minute or two in and then skip to the next song. As one of the ENV values I have set the cache to be 25 GB. I have also attempted to clear the /cache folder in the /data directory.

**Logs**

```
due to length, can be found here:  https://pastebin.com/x2H1Nnbx

(will be deleted within 2 weeks)

```

**Screenshots**

**Additional context**

**Runtime**
I'm running Muse:
- [ ] Directly from the cloned repository
- [X] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: 2.1.7
- Docker (if applicable): 20.10.18
- OS: Ubuntu 20 LTS
- Node.js: (if running outside the Docker container)
- ffmpeg: (if running outside the Docker container, 4.1 or later is required)

**Comment by codetheweb** [comment]
Thanks for the report. I'm having a hard time reproducing this, does the bug occur for you with `/play https://www.youtube.com/watch?v=n61ULEU7CO0&list=PL6NdkXsPL07KN01gH2vucrHCEyyNmVEx4` in an empty queue?

**Comment by ModernChaot** [comment]
![image](https://user-images.githubusercontent.com/25331228/193107230-58429a96-3a2e-4b23-8bea-4ea44dea0869.png)

Unfortunately it still does and skips to the next song in the playlist. I'll try migrating it to another docker host (currently running on a Linode 2 GB ubuntu box) to see if I can reproduce the issue on another system or if it's just a config issue on my side.

**Comment by ModernChaot** [comment]
Well, this is awkward. Moved it to another docker host and it runs without issues... I have a feeling that something with the docker host config was amiss causing trouble.

Thanks for looking, closing issue!
