### ISSUE TITLE
Implement SponsorBlock

### ISSUE THREAD

**Issue by FuJa0815** [codetheweb/muse#808]
SponsorBlock is a system for marking sponsored sections, self promotion, interaction reminder, credits, intros, non-music sections in a music videos and various other sections. The SponsorBlock browser plugin allows the automatic skipping of these sections, if desired. Due to this being FOSS and allowing third party APIs it should be possible to integrate this system into the bot.

I'll try implementing this myself after getting used to the code.

**Comment by codetheweb** [comment]
This is a really cool idea but I'm not sure how useful it would be if most users are using Muse for music. Interested in seeing how complex the implementation is.

**Comment by FuJa0815** [comment]
SponsorBlock marks non-music sections in music videos, like 0:00-1:46 on https://youtu.be/F2AitTPI5U0
Here is the API specification of SponsorBlock: https://wiki.sponsor.ajay.app/w/API_Docs
I've started reading through the code a bit, shouldn't be too hard to implement some additional Configs and a SponsorBlock API-Call in the YouTube service.

**Comment by xHyperElectric** [comment]
This would be a really awesome thing to see so that sections of youtube music videos could be automatically skipped with some sponsor block configuration.

**Comment by Charlignon** [comment]
Really like the idea as well !
