### ISSUE TITLE
Enhancement: Volume control

### ISSUE THREAD

**Issue by Peppershade** [codetheweb/muse#830]
I love the project, however we cannot use it in our setup because there is no volume control. Is there a chance it will be added in the future?
We use Discord with a listening bot to make the audio available on a speaker system using a Raspberry Pi, however we cannot access the volume from there easily.

**Comment by codetheweb** [comment]
That's an interesting use case. I generally feel that volume controls are unnecessary bloat at best or actively hostile at worst (if the bot owner chooses a default volume that doesn't work for >50% of listeners), but I see how it'd be useful in your case.

No guarantees that I'll accept a PR for this but if you (or someone else) prepares a PR I'll take a look.

**Comment by matiasba** [comment]
Really hope that something like this could be added in the future. I really like the bot but the default volume seems really loud for everyone in my server.

**Comment by Raecaug** [comment]
I believe this can already be tweaked on a per-user basis via [this method](https://support.discord.com/hc/en-us/articles/205287897-How-do-I-adjust-the-volume-level-of-individual-users-in-my-server-).

**Comment by FoxxMD** [comment]
@matiasba I've got a PR in for this. You can try using docker image `foxxmd/muse:latest` with the additional env `VOLUME_CONTROL=true` added to your run command.
