### ISSUE TITLE
Error ope: Could not find settings for guild - after it's been working

### ISSUE THREAD

**Issue by labmonjos** [codetheweb/muse#866]
Hello,

I am running Muse in an Unraid Docker, running the latest version. I have had some difficulty starting it up, but once it's working, it worked fine!

I have noticed today, the Docker was spitting out this error: "ope: Could not find settings for guild". I have seen others say to uninvite and reinvite to get it working the first time, but this wasn't a first time install and has been working for months (minus the occasional crashes). Now, uninviting and reinventing DID work, but how can I prevent this from happening in the future?

also i am running this fix on the docker if that's any help. otherwise this is all stock:
https://github.com/codetheweb/muse/issues/840#issuecomment-1332711211

Screenshots
![image](https://user-images.githubusercontent.com/77901916/213945681-b6cccb4b-f3a4-4983-aa07-bca42d417b9e.png)
![image](https://user-images.githubusercontent.com/77901916/213945929-f5d2a241-d926-4dfc-abe8-dc2c7c76f408.png)

Additional context
see above
also saw the above in the muse logs. not sure if its related but it was recent.

Runtime
I'm running Muse:

- [no] Directly from the cloned repository
- [YES] Inside a Docker container
- [n/a] Something else (please elaborate)

Versions

Muse: 2.1.7
Docker (if applicable): 20.10.5
OS: Unraid 6.9.2
ffmpeg: n/a

Thanks,

**Comment by codetheweb** [comment]
Did you mount a persistent data directory from the host into the container?

The error is thrown when Muse is in a guild that it doesn't know about.

**Comment by SushiWaUmai** [comment]
Had the same problem but could fix it by inviting the bot via the link that is logged from the container.

**Comment by labmonjos** [comment]
> Did you mount a persistent data directory from the host into the container?
> 
> The error is thrown when Muse is in a guild that it doesn't know about.

I am running the docker as default in unRAID so I assume I am not. I will look over this and see if I can get a persistent directory.

**Comment by labmonjos** [comment]
sorry for the slow replies. I do not know much about this stuff (network admin)... but enough to be dangerous!

So i went into the CLI and made a new docker volume. I removed the old container and remade the container with the following:

`docker run -it -d -v muse_persist:/data -e *tokens go here*`

I can verify that its using a named container with this command:
![image](https://user-images.githubusercontent.com/77901916/221994948-7210bc5f-39e4-4743-9bbd-12f60060d50c.png)

Should this take care of it? Or am I looking down the wrong rabbit hole?

**Comment by codetheweb** [comment]
That seems like it should do it. 👍

**Comment by labmonjos** [comment]
Thank you for confirming!! I'll close out the ticket. :)
