### ISSUE TITLE
No audio when bot joins channel 

### ISSUE THREAD

**Issue by ThatGuy52** [codetheweb/muse#894]
Either im retarded and should just find another bot or i did something wrong and the bot is refusing to play any audio. Everytime i queue up a song it accepts it the bot joins the channel and then it just sits their with no audio coming through at all. Makes 0 sense.
https://Disney.is-a-bad.host/i/slhej.png

shows that its playing but the bot isnt sending any audio, did i miss a step?

Im running this in a windows server with FFMPEG path set and whatnot.

**Comment by codetheweb** [comment]
Sorry, but I can't help without more information. Please open a new issue and [follow this issue template](https://github.com/codetheweb/muse/issues/new?assignees=&labels=support&template=support-request.md&title=).
