### ISSUE TITLE
Its not using spotify

### ISSUE THREAD

**Issue by carolynsteeves1** [codetheweb/muse#916]
**What's happening?**
When i play a song and select spotify it still grabs it from youtube. When i try paste in an playlist from spotify, it fetches it all from youtube

**Logs**

```


**Runtime**
I'm running Muse:
- [ ] Directly from the cloned repository
- [ x] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: Newest version
- Docker (if applicable):
- OS: Arm64
- Node.js: (if running outside the Docker container)
- ffmpeg: (if running outside the Docker container, 4.1 or later is required)

**Comment by Jelbrekinator** [comment]
It’s working as intended, the bot attempts to find the correct song via YouTube and plays that instead. Presumably it’s done this way so that Spotify Premium isn't required unlike the other music bots that support Spotify

**Comment by codetheweb** [comment]
If you want something that actually streams from Spotify, I'd recommend checking out [Aoede](https://github.com/codetheweb/aoede).
