### ISSUE TITLE
request: updating currently playing message

### ISSUE THREAD

**Issue by Scraft08YT** [codetheweb/muse#917]

**Comment by codetheweb** [comment]
Can you please expand on what this feature request is?

**Comment by Scraft08YT** [comment]
Sure.
When you play a song or you use /now-playing, the bot posts a message with a timeline where you can see how long the song has been playing. But it's just static and it would be cool, if the last message would get updated until a new /now-playing is triggered.

**Comment by codetheweb** [comment]
I can't find it now but I did start implementing this at one point. We decided not to do it, though I can't remember the exact reasons.

This does something similar that may work for your use case: https://github.com/codetheweb/muse/pull/914
