### ISSUE TITLE
[Feature Request] Call now playing command at the start of a new song

### ISSUE THREAD

**Issue by the-Astra** [codetheweb/muse#930]
It would be very nice to have the bot call the now playing command or a similar new command at the start of a new song to easily glance at the bot's channel to see what's playing as opposed to the user calling the command each time. Many other bots do this and is very useful, and would very much like to see this implemented here as well. 

This is kind of a repeat of #831 but since this hasn't been implemented I thought I'd bring it up again.

**Comment by codetheweb** [comment]
Duplicate of #831, please track progress there :)
