### ISSUE TITLE
Feature Request: Auto-play from local folder

### ISSUE THREAD

**Issue by sypion** [codetheweb/muse#944]
I'd love the ability to place some of my current music in a local folder, likely where Muse currently resides, for it to play songs when the queue is empty.

Ex: Muse will play music from a local folder automatically when no songs are queued. It could also resume the last played song when it joins a voice channel.

**Comment by codetheweb** [comment]
Although https://github.com/codetheweb/muse/issues/299 was filed a while ago, the reasoning there still applies.

**Comment by sypion** [comment]
Ooh, I see. No worries then. Thanks @codetheweb!
