### ISSUE TITLE
[/play] Invalid prisma.keyValueCache.upsert() invocation

### ISSUE THREAD

**Issue by notevanrutten** [codetheweb/muse#947]
**What's happening?**
Receiving the error `Invalid prisma.keyValueCache.upsert() invocation` when using the `/play` command for a YouTube query.

**Logs**
```
Invalid prisma.keyValueCache.upsert() invocation:


  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(SqliteFailure(Error { code: DatabaseCorrupt, extended_code: 11 }, Some("database disk image is malformed"))) })
```

**Runtime**
I'm running Muse:
- [x] Directly from the cloned repository
- [ ] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: 2.3.0
- Docker: N/A
- OS: Fedora 37
- Node.js: 16.18.1
- ffmpeg: 5.1.3

**Comment by notevanrutten** [comment]
Update: I'm now getting the error `Response code 403 (Forbidden)`

There are now logs from the console on my Linux machine:
```
Error: 
Invalid `prisma.setting.upsert()` invocation:


  Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(SqliteFailure(Error { code: ReadOnly, extended_code: 1032 }, Some("attempt to write a readonly database"))) })
    at RequestHandler.handleRequestError (/home/evanrutten/Documents/muse/node_modules/@prisma/client/runtime/index.js:28662:13)
    at RequestHandler.request (/home/evanrutten/Documents/muse/node_modules/@prisma/client/runtime/index.js:28640:12)
    at consumer (/home/evanrutten/Documents/muse/node_modules/@prisma/client/runtime/index.js:29618:18)
    at PrismaClient._request (/home/evanrutten/Documents/muse/node_modules/@prisma/client/runtime/index.js:29639:16)
    at Client.guild_create_default (/home/evanrutten/Documents/muse/src/events/guild-create.ts:24:3) {
  clientVersion: '4.1.1'
}
```

Looks like it has to do with read-only files. What should I do to fix this?

**Comment by codetheweb** [comment]
I would try deleting the database file. Is it writable by whatever user the Node process is running as?

**Comment by notevanrutten** [comment]
I tried running `chmod 777 muse/` to enable permissions for all files in the folder. Now I'm getting a new error in Discord:

🚫 ope: filterWrapper is not iterable

**Comment by codetheweb** [comment]
There should be a full stack trace in your console, can you paste that?

**Comment by notevanrutten** [comment]
Alright, I've enabled `DEBUG=*` in the .env file. Here are the logs:

```  muse Cache miss: [{"searchParams":{"part":"id, snippet, contentDetails","id":"F0crqDcRbic"}}] +1s
  muse HTTPError: Response code 403 (Forbidden)
  muse     at Request.<anonymous> (/home/evanrutten/muse/node_modules/got/dist/source/as-promise/null:86:42)
  muse     at Object.onceWrapper (node:events:628:26)
  muse     at Request.emit (node:events:525:35)
  muse     at Request._onResponseBase (/home/evanrutten/muse/node_modules/got/dist/source/core/null:727:22)
  muse     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  muse     at Request._onResponse (/home/evanrutten/muse/node_modules/got/dist/source/core/null:766:13) +249ms```

**Comment by codetheweb** [comment]
I would double check your `YOUTUBE_API_KEY` and make sure it's correct.

**Comment by notevanrutten** [comment]
You were correct, the issue was that the API key I created was not directly linked to the Youtube Data API. I made a new one that was properly linked and everything works as expected. Thanks!

**Comment by notevanrutten** [comment]
Closed.
