### ISSUE TITLE
🚫 ope: filterWrapper is not iterable

### ISSUE THREAD

**Issue by Kinuseka** [codetheweb/muse#948]
**What's happening?**
Concisely describe what's going wrong.

**Logs**

logs seems to be not found on console

**Additional context**
This error occurs randomly while using `/play` 
Confirmed that this is not a user error seems to be the server side. 

**Runtime**
I'm running Muse:
- [x] Directly from the cloned repository
- [ ] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: 2.3.0
- Docker (if applicable):
- OS: Ubuntu v20.04
- Node.js:  v16.20.0
- ffmpeg: 4.2.7-0ubuntu0.1

**Comment by codetheweb** [comment]
Did you try running with `DEBUG=*` to see if more error details are logged?

**Comment by Kinuseka** [comment]
Gotcha
```
 prisma:client:libraryEngine  sending request, this.libraryStarted: true +1s
  muse Cache miss: ["tokyo rain marcus warner",{"limit":10}] +4s
  muse /home/user/muse/node_modules/ytsr/lib/utils.js:23
  muse   for (const filterGroup of filterWrapper) {
  muse                             ^
  muse
  muse TypeError: filterWrapper is not iterable
  muse     at Object.exports.parseFilters (/home/user/muse/node_modules/ytsr/lib/utils.js:23:29)
  muse     at module.exports (/home/user/muse/node_modules/ytsr/lib/main.js:60:24)
  muse     at runMicrotasks (<anonymous>)
  muse     at processTicksAndRejections (node:internal/process/task_queues:96:5)
  muse     at KeyValueCacheProvider.wrap (/home/user/muse/src/services/key-value-cache.ts:53:20)
  muse     at run (/home/user/muse/node_modules/p-queue/dist/null:109:36) +2s
```

This is the error I caught, the error is pretty inconsistent sometimes it works and sometimes it doesnt. Hopefully we can make this solve this inconsistency

**Comment by codetheweb** [comment]
Looks like this is a bug with the ytsr package: https://github.com/TimeForANinja/node-ytsr/issues/180

**Comment by nullcreek** [comment]
Getting an identical error using the latest release through Docker on a fresh install of Ubuntu 22.04. Tried installing a few months ago on a completely different machine through the basic Node.js install route and got the same error. Is there a known fix I'm missing?
 
```
  prisma:client:libraryEngine  sending request, this.libraryStarted: true +154ms
  muse Cache miss: ["fart sounds",{"limit":10}] +10s
  muse /usr/app/node_modules/ytsr/lib/utils.js:23
  muse   for (const filterGroup of filterWrapper) {
  muse                             ^
  muse
  muse TypeError: filterWrapper is not iterable
  muse     at Object.exports.parseFilters (/usr/app/node_modules/ytsr/lib/utils.js:23:29)
  muse     at module.exports (/usr/app/node_modules/ytsr/lib/main.js:60:24)
  muse     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  muse     at KeyValueCacheProvider.wrap (/usr/app/src/services/key-value-cache.ts:53:20)
  muse     at run (/usr/app/node_modules/p-queue/dist/null:109:36) +676ms
```

**Comment by JosephBerman** [comment]
I am also getting this same error, on latest release

**Comment by hemantgogia09** [comment]
+1 happening to me as well using latest docker build

**Comment by LeonardoLeoo89** [comment]
happening to me as well, latest docker release

**Comment by Frobby01** [comment]
+1

**Comment by cunhar** [comment]
+1

**Comment by MathiasDevelopes** [comment]
+1 latest docker

**Comment by Avapaa** [comment]
Same issue, downgraded to codetheweb/muse:2.2.4 for now...

**Comment by Bones3951** [comment]
+1 experiencing this issue, latest version and 2.2.4 as well

**Comment by drpepper66** [comment]
this issue used to be sporadic, but after a while of running the bot, it occurs on literally every play command (no matter if the input is a search query, spotify or youtube url), rendering the bot entirely unusuable. I would suggest that node-ytsr is forked. in the meantime, I applied the ytsr fix in my docker-compose setup like so in order to avoid building my own image:

```

  muse:
    image: codetheweb/muse:2.4.1
    restart: always
    volumes:
      - ./muse:/data
    entrypoint: bash
    # hotfix for https://github.com/codetheweb/muse/issues/948
    command: -c "sed -i 's/of filterWrapper[)]/of filterWrapper|| [])/g' /usr/app/node_modules/ytsr/lib/utils.js && tini -- yarn start"
```

**Comment by lilkingjr1** [comment]
@drpepper66 This worked for me! Thank you!

P.S. Could the sporadic nature be due to Muse's caching? I know nothing about this project yet, so sorry if this is a dumb question.

**Comment by SeiRann** [comment]
how do you do that but with node?

**Comment by Bones3951** [comment]
> how do you do that but with node?

1) Stop the bot
2) Go into your bot's folder and then run that command:

sed -i 's/of filterWrapper[)]/of filterWrapper|| [])/g' /node_modules/ytsr/lib/utils.js

3) Restart the bot, npm run start.

**Comment by codetheweb** [comment]
I don't have the time right now, but if anyone else is interested in fixing this I think we could completely drop the `node-ytsr` dependency and query for tracks using Google's official API since we have an `YOUTUBE_API_KEY` anyways.

**Comment by MrManiacc** [comment]
As per this [this github issue](https://github.com/TimeForANinja/node-ytsr/issues/180#issuecomment-1507709961), to fix all you have to do is edit `node_modules\ytsr\lib\utils.js`.  Change line **l`21`** as follows

before
`const filterWrapper = (wrapper.subMenu || wrapper.submenu).searchSubMenuRenderer.groups;`

after
`const filterWrapper = (wrapper.subMenu || wrapper.submenu).searchSubMenuRenderer.groups || [];`

**Comment by Kinuseka** [comment]
> I don't have the time right now, but if anyone else is interested in fixing this I think we could completely drop the `node-ytsr` dependency and query for tracks using Google's official API since we have an `YOUTUBE_API_KEY` anyways.

since the API is pretty limited, I believe we can use the API as a failure fallback while keeping ytsr as the main search engine.

**Comment by EugeneLeclerc** [comment]
Looks like the problem was fixed on https://github.com/TimeForANinja/node-ytsr/pull/203

**Comment by cRaZy92** [comment]
Running the bot for the first time using docker image (latest 2.4.2 version) and I have the same problem. :(

**Comment by EugeneLeclerc** [comment]
> Running the bot for the first time using docker image (latest 2.4.2 version) and I have the same problem. :(

@cRaZy92 do you have any logs? 2.4.2 completely solved the issue for me.

**Comment by cRaZy92** [comment]
> @cRaZy92 do you have any logs? 2.4.2 completely solved the issue for me.

Never mind, it only happened with one specific track on Spotify, sorry for the false alarm. Thank you anyways!
