### ISSUE TITLE
Bug: Embedded player not working

### ISSUE THREAD

**Issue by dverborgh** [codetheweb/muse#951]
**What's happening?**
The bot works perfectly fine, except for the embedded player, which loads and then is frozen. None of the buttons or progress bar work or do anything. 
I've tried running several versions from docker and all of them have the same behavior (specifically, :latest, :2 and :2.2), and this problem also presents with other people on the same discord servers that I've tried the bot on.

**Screenshots**
![image](https://github.com/codetheweb/muse/assets/94992483/752b7c77-214e-484e-bfa6-436cf1140e73)

**Additional context**

**Runtime**
I'm running Muse:
- [X ] Inside a Docker container

**Versions**
- Muse: :2, :2.2 and :latest
- Docker (if applicable): version 20.10.13, build a224086
- OS: Ubuntu 20.04.3 LTS

**Comment by codetheweb** [comment]
The embed is not interactive.
