### ISSUE TITLE
Bot consumes a lot of disk space

### ISSUE THREAD

**Issue by Scraft08YT** [codetheweb/muse#952]
So in my case the bot uses so much, that it overshoots the limits of my hoster, so I can't use it at the moment. I wanted to ask, what files can be deleted without making any problems.

**Comment by Kinuseka** [comment]
Did you set the `.env`  and include `CACHE_LIMIT`?
I set mine to `CACHE_LIMIT=2GB` and you can use your own configuration to your liking.

**Comment by codetheweb** [comment]
As @Kinuseka mentioned, the correct way to control this is with the `CACHE_LIMIT` env var. The default limit is 2GB.
