### ISSUE TITLE
Bot always joins a channel with itself muted.

### ISSUE THREAD

**Issue by Dan-Mizu** [codetheweb/muse#961]
**What's happening?**
Whenever the bot joins a channel to play music, it has itself muted. I have to manually Server Mute and Server Unmute it. Happens whenever it leaves the channel and joins again.

**Runtime**
I'm running Muse:
- [ ] Directly from the cloned repository
- [X] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: v2.4.2
- Docker (if applicable): v24.0.5
- OS: Linux (Ubuntu v22.04)
- Node.js: (if running outside the Docker container)
- ffmpeg: (if running outside the Docker container, 4.1 or later is required)

**Comment by codetheweb** [comment]
Muse doesn't mute itself, so it's probably something in your server config.
