### ISSUE TITLE
YouTube /play is broken

### ISSUE THREAD

**Issue by Frorayz** [codetheweb/muse#969]
**What's happening?**

I am using the NPM mode, and I am getting this while trying to play any youtube irl.

<img width="324" alt="Screen Shot 2023-09-03 at 2 59 39 PM" src="https://github.com/codetheweb/muse/assets/32178410/10d7f21f-790a-43d0-8729-c5b036f8451f">

I am using different project's API key for YouTube (have two instances of the bot). But I am guessing they blocked me somehow??

Would appreciate any help!

**Logs**

```
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: true +78ms
  muse [VOICE] received voice server: {"t":"VOICE_SERVER_UPDATE","s":9,"op":0,"d":{"token":"xxx","guild_id":"xxx","endpoint":"us-east9006.discord.media:443"}} +71ms
  prisma:client  Prisma Client call: +2s
  prisma:client  prisma.setting.findUnique({
  where: {
    guildId: 'xxx'
  }
}) +0ms
  prisma:client  Generated request: +0ms
  prisma:client  query {
  findUniqueSetting(where: {
    guildId: "xxx"
  }) {
    guildId
    playlistLimit
    secondsToWaitAfterQueueEmpties
    leaveIfNoListeners
    createdAt
    updatedAt
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: true +2s
  muse Error: Status code: 429
  muse     at ClientRequest.<anonymous> (/home/rayz/music/node_modules/miniget/dist/index.js:199:31)
  muse     at Object.onceWrapper (node:events:629:26)
  muse     at ClientRequest.emit (node:events:514:28)
  muse     at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)
  muse     at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
  muse     at TLSSocket.socketOnData (node:_http_client:541:22)
  muse     at TLSSocket.emit (node:events:514:28)
  muse     at addChunk (node:internal/streams/readable:324:12)
  muse     at readableAddChunk (node:internal/streams/readable:297:9)
  muse     at Readable.push (node:internal/streams/readable:234:10) +2s
  muse [WS => Shard 0] Heartbeat acknowledged, latency of 19ms. +7s

```

**Runtime**
I'm running Muse:
- [x] Directly from the cloned repository

**Versions**
- Muse: latest
- OS: Ubuntu 22.04
- Node.js: 18 LTS
- ffmpeg: 4.4.2-0ubuntu0.22.04.1

**Comment by turikhay** [comment]
Same here. How did you work around this?

**Comment by fmunim** [comment]
> Same here. How did you work around this?
> 
> _UPD_ My server IP seems to be banned or heavily rate-limited. Ugh. Works OK from my home (same tokens, just a residential IP).
> 
> I can reproduce this reliably with [very long](https://www.youtube.com/watch?v=Fplc7bUc-FM) or [livestreams tracks](https://www.youtube.com/watch?v=jfKfPfyJRdk).
> Sample from logs
> 
> ```
> muse-muse-1  | 2023-09-19T15:50:32.025Z muse /usr/app/node_modules/miniget/dist/index.js:199
> muse-muse-1  |                     let err = new Miniget.MinigetError(`Status code: ${res.statusCode}`, res.statusCode);
> muse-muse-1  |                               ^
> muse-muse-1  |
> muse-muse-1  | Error: Status code: 429
> muse-muse-1  |     at ClientRequest.<anonymous> (/usr/app/node_modules/miniget/dist/index.js:199:31)
> muse-muse-1  |     at Object.onceWrapper (node:events:628:26)
> muse-muse-1  |     at ClientRequest.emit (node:events:513:28)
> muse-muse-1  |     at HTTPParser.parserOnIncomingClient (node:_http_client:674:27)
> muse-muse-1  |     at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
> muse-muse-1  |     at TLSSocket.socketOnData (node:_http_client:521:22)
> muse-muse-1  |     at TLSSocket.emit (node:events:513:28)
> muse-muse-1  |     at addChunk (node:internal/streams/readable:324:12)
> muse-muse-1  |     at readableAddChunk (node:internal/streams/readable:297:9)
> muse-muse-1  |     at Readable.push (node:internal/streams/readable:234:10)
> ```

It eventually resolved itself. YouTube rate-limited you, you can change your ip and it would then work. But for me it just resolved in a day on its own.
