### ISSUE TITLE
Invalid or unexpected token

### ISSUE THREAD

**Issue by nermish** [codetheweb/muse#970]
**What's happening?**
all /play commands result in the error '🚫 ope: Invalid or unexpected token.'
problem persists after recreation, and after regenerating discord token. 

**Logs**

```
root@462dd7e4c15e:/usr/app# DEBUG=* yarn start
yarn run v1.22.19
$ npm run env:set-database-url -- tsx src/scripts/migrate-and-start.ts

> muse@2.4.2 env:set-database-url
> tsx src/scripts/run-with-database-url.ts

  prisma:tryLoadEnv  Environment variables not found at null +0ms
  prisma:tryLoadEnv  Environment variables not found at undefined +1ms
  prisma:tryLoadEnv  No Environment variables loaded +0ms
  prisma:tryLoadEnv  Environment variables not found at null +531ms
  prisma:tryLoadEnv  Environment variables not found at undefined +0ms
  prisma:tryLoadEnv  No Environment variables loaded +0ms
  prisma:client  dirname /usr/app/node_modules/.prisma/client +0ms
  prisma:client  relativePath ../../.. +0ms
  prisma:client  cwd /usr/app +0ms
  prisma:client  clientVersion: 4.1.1 +2ms
  prisma:client  clientEngineType: library +0ms
  prisma:client:libraryEngine  internalSetup +0ms
  prisma:tryLoadEnv  Environment variables not found at null +701ms
  prisma:tryLoadEnv  Environment variables not found at undefined +0ms
  prisma:tryLoadEnv  No Environment variables loaded +0ms
  prisma:client  dirname /usr/app/node_modules/.prisma/client +699ms
  prisma:client  relativePath ../../.. +1ms
  prisma:client  cwd /usr/app +1ms
  prisma:client  clientVersion: 4.1.1 +0ms
  prisma:client  clientEngineType: library +0ms
  prisma:client:libraryEngine  internalSetup +701ms
========================================
========================================
================= muse =================
========================================
=========== Made with 🎶 by ============
==== https://github.com/codetheweb =====
========================================
========================================

Running version 2.4.2 built on 8/12/2023 (commit f1f6ee7e8975f1333f9b39af439be70f34abf5ee)

🔧 Need help? https://github.com/codetheweb/muse/discussions/new
🐛 Bug? https://github.com/codetheweb/muse/issues/new
✨ New feature? https://github.com/codetheweb/muse/issues/new
☕ Discussion? https://github.com/codetheweb/muse/discussions/new
💰 Help me? https://www.paypal.me/codetheweb https://github.com/sponsors/codetheweb


⠋ Applying database migrations...  prisma:client  prisma.queryRaw(SELECT COUNT(id) FROM _prisma_migrations, []) +80ms
  prisma:client  Prisma Client call: +0ms
⠙ Applying database migrations...  prisma:client:libraryEngine:loader  Searching for Query Engine Library in /usr/app/node_modules/.prisma/client +0ms
  prisma:client:libraryEngine:loader  loadEngine using /usr/app/node_modules/.prisma/client/libquery_engine-debian-openssl-1.1.x.so.node +0ms
  prisma:client  Prisma Client call: +110ms
  prisma:client  prisma.$queryRaw({
  query: 'SELECT COUNT(id) FROM _prisma_migrations',
  parameters: {
    values: '[]',
    __prismaRawParamaters__: true
  }
}) +2ms
  prisma:client  Generated request: +0ms
  prisma:client  mutation {
  queryRaw(
    query: "SELECT COUNT(id) FROM _prisma_migrations"
    parameters: "[]"
  )
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: false +193ms
  prisma:client:libraryEngine  library starting +1ms
  prisma:client:libraryEngine:loader  Searching for Query Engine Library in /usr/app/node_modules/.prisma/client +27ms
  prisma:client:libraryEngine:loader  loadEngine using /usr/app/node_modules/.prisma/client/libquery_engine-debian-openssl-1.1.x.so.node +0ms
  prisma:client:libraryEngine  library started +3ms
✔ Database migrations applied.
  prisma:client  Prisma Client call: +2s
  prisma:client  prisma.fileCache.findMany({
  where: undefined,
  orderBy: {
    createdAt: 'asc'
  },
  take: 50
}) +1ms
  prisma:client  Generated request: +0ms
  prisma:client  query {
  findManyFileCache(
    orderBy: [
      {
        createdAt: asc
      }
    ]
    take: 50
  ) {
    hash
    bytes
    accessedAt
    createdAt
    updatedAt
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: false +2s
  prisma:client:libraryEngine  library starting +0ms
  prisma:client:libraryEngine  library started +2ms
  muse Evicting oldest files... +0ms
  prisma:client  Prisma Client call: +7ms
  prisma:client  prisma.fileCache.aggregate({
  select: {
    _sum: {
      select: {
        bytes: true
      }
    }
  }
}) +0ms
  prisma:client  Generated request: +0ms
  prisma:client  query {
  aggregateFileCache {
    _sum {
      bytes
    }
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: true +5ms
  superagent POST https://accounts.spotify.com/api/token +0ms
  superagent POST https://accounts.spotify.com/api/token +7ms
⠋ 📡 connecting to Discord...  muse Provided token: MTEyNzgyNDYyNDYzODUwNDk4MQ.GJCFZv.************************************** +38ms
  muse Preparing to connect to the gateway... +0ms
  muse No files needed to be evicted. Total size of the cache is currently 0 bytes, and the cache limit is 2000000000 bytes. +13ms
⠙ 📡 connecting to Discord...  superagent POST https://accounts.spotify.com/api/token -> 200 +125ms
  superagent POST https://accounts.spotify.com/api/token -> 200 +23ms
⠹ 📡 connecting to Discord...  muse [WS => Manager] Fetched Gateway Information
  muse     URL: wss://gateway.discord.gg
  muse     Recommended Shards: 1 +201ms
  muse [WS => Manager] Session Limit Information
  muse     Total: 1000
  muse     Remaining: 990 +0ms
  muse [WS => Shard 0] Connecting to wss://gateway.discord.gg?v=10&encoding=json +4ms
  muse [WS => Shard 0] Waiting for event hello for 60000ms +4ms
⠼ 📡 connecting to Discord...  muse [WS => Shard 0] Preparing first heartbeat of the connection with a jitter of 0.40485230475059053; waiting 16700ms +146ms
  muse [WS => Shard 0] Waiting for identify throttle +1ms
  muse [WS => Shard 0] Identifying
  muse  shard id: 0
  muse  shard count: 1
  muse  intents: 1153
  muse  compression: none +1ms
  muse [WS => Shard 0] Waiting for event ready for 15000ms +1ms
⠇ 📡 connecting to Discord...  muse [WS => Shard 0] Shard received all its guilds. Marking as fully ready. +301ms
  muse --------------------------------------------------
  muse Core Dependencies
  muse - @discordjs/voice: 0.11.0
  muse - prism-media: 1.3.4
  muse
  muse Opus Libraries
  muse - @discordjs/opus: 0.8.0
  muse - opusscript: not found
  muse
  muse Encryption Libraries
  muse - sodium-native: not found
  muse - sodium: not found
  muse - libsodium-wrappers: 0.7.10
  muse - tweetnacl: not found
  muse
  muse FFmpeg
  muse - version: 4.3.6-0+deb11u1
  muse - libopus: yes
  muse -------------------------------------------------- +3ms
✔ Ready! Invite the bot with https://discordapp.com/oauth2/authorize?client_id=1127824624638504981&scope=bot%20applications.commands&permissions=36700160
  muse /usr/app/node_modules/discord.js/node_modules/@discordjs/rest/dist/index.js:640
  muse       throw new DiscordAPIError(data, "code" in data ? data.code : data.error, status, method, url, requestData);
  muse             ^
  muse
  muse DiscordAPIError[10062]: Unknown interaction
  muse     at handleErrors (/usr/app/node_modules/discord.js/node_modules/@discordjs/rest/dist/index.js:640:13)
  muse     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  muse     at BurstHandler.runRequest (/usr/app/node_modules/discord.js/node_modules/@discordjs/rest/dist/index.js:736:23)
  muse     at REST.request (/usr/app/node_modules/discord.js/node_modules/@discordjs/rest/dist/index.js:1387:22)
  muse     at AutocompleteInteraction.respond (/usr/app/node_modules/discord.js/src/structures/AutocompleteInteraction.js:86:5)
  muse     at play_default.handleAutocompleteInteraction (/usr/app/src/commands/play.ts:62:7)
  muse     at Client.<anonymous> (/usr/app/src/bot.ts:99:13) +6s
  prisma:client  Prisma Client call: +7s
  prisma:client  prisma.keyValueCache.findUnique({
  where: {
    key: 'autocomplete:https://youtu.be/MIxowl5YuaQ'
  }
}) +0ms
  prisma:client  Generated request: +0ms
  prisma:client  query {
  findUniqueKeyValueCache(where: {
    key: "autocomplete:https://youtu.be/MIxowl5YuaQ"
  }) {
    key
    value
    expiresAt
    createdAt
    updatedAt
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: true +7s
  muse Cache hit: autocomplete:https://youtu.be/MIxowl5YuaQ +537ms
  muse /usr/app/node_modules/discord.js/node_modules/@discordjs/rest/dist/index.js:640
  muse       throw new DiscordAPIError(data, "code" in data ? data.code : data.error, status, method, url, requestData);
  muse             ^
  muse
  muse DiscordAPIError[40060]: Interaction has already been acknowledged.
  muse     at handleErrors (/usr/app/node_modules/discord.js/node_modules/@discordjs/rest/dist/index.js:640:13)
  muse     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  muse     at BurstHandler.runRequest (/usr/app/node_modules/discord.js/node_modules/@discordjs/rest/dist/index.js:736:23)
  muse     at REST.request (/usr/app/node_modules/discord.js/node_modules/@discordjs/rest/dist/index.js:1387:22)
  muse     at AutocompleteInteraction.respond (/usr/app/node_modules/discord.js/src/structures/AutocompleteInteraction.js:86:5)
  muse     at play_default.handleAutocompleteInteraction (/usr/app/src/commands/play.ts:84:5)
  muse     at Client.<anonymous> (/usr/app/src/bot.ts:99:13) +80ms
  prisma:client  Prisma Client call: +5s
  prisma:client  prisma.setting.findUnique({
  where: {
    guildId: '795537201126834217'
  }
}) +0ms
  prisma:client  Generated request: +0ms
  prisma:client  query {
  findUniqueSetting(where: {
    guildId: "795537201126834217"
  }) {
    guildId
    playlistLimit
    secondsToWaitAfterQueueEmpties
    leaveIfNoListeners
    createdAt
    updatedAt
  }
}
 +0ms
  prisma:client:libraryEngine  sending request, this.libraryStarted: true +5s
  muse /usr/app/node_modules/discord.js/node_modules/@discordjs/rest/dist/index.js:640
  muse       throw new DiscordAPIError(data, "code" in data ? data.code : data.error, status, method, url, requestData);
  muse             ^
  muse
  muse DiscordAPIError[10062]: Unknown interaction
  muse     at handleErrors (/usr/app/node_modules/discord.js/node_modules/@discordjs/rest/dist/index.js:640:13)
  muse     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  muse     at BurstHandler.runRequest (/usr/app/node_modules/discord.js/node_modules/@discordjs/rest/dist/index.js:736:23)
  muse     at REST.request (/usr/app/node_modules/discord.js/node_modules/@discordjs/rest/dist/index.js:1387:22)
  muse     at ChatInputCommandInteraction.deferReply (/usr/app/node_modules/discord.js/src/structures/interfaces/InteractionResponses.js:69:5)
  muse     at AddQueryToQueue.addToQueue (/usr/app/src/services/add-query-to-queue.ts:42:5)
  muse     at play_default.execute (/usr/app/src/commands/play.ts:49:5)
  muse     at Client.<anonymous> (/usr/app/src/bot.ts:79:13) +5s
  muse [VOICE] received voice state update: {"member":{"user":{"username":"Solid Astolfo","public_flags":0,"id":"1127824624638504981","global_name":null,"display_name":null,"discriminator":"4497","bot":true,"avatar_decoration_data":null,"avatar":"66083a877400c4162610dcf14504a104"},"roles":["1127827198934519872"],"premium_since":null,"pending":false,"nick":null,"mute":false,"joined_at":"2023-07-10T05:02:38.299102+00:00","flags":0,"deaf":false,"communication_disabled_until":null,"avatar":null},"user_id":"1127824624638504981","suppress":false,"session_id":"c7da0ba914ef751c836028520e2fc4cf","self_video":false,"self_mute":false,"self_deaf":true,"request_to_speak_timestamp":null,"mute":false,"guild_id":"795537201126834217","deaf":false,"channel_id":"1027427371927752794"} +130ms
  muse [WS => Shard 0] First heartbeat sent, starting to beat every 41250ms +5s
  muse [WS => Shard 0] Heartbeat acknowledged, latency of 43ms. +43ms
```

**Screenshots**

**Additional context**
Bot has been working fine, last successful command was sent today at around 5pm. Unsure what could have changed, the last successful command and the first failed one were 3 minutes apart.

**Runtime**
I'm running Muse:
- [ ] Directly from the cloned repository
- [X ] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: 2.4.2
- Docker (if applicable): Docker version 20.10.24, build 297e128
- OS: Ubuntu 22.04.2 LTS
- Node.js: (if running outside the Docker container)
- ffmpeg: (if running outside the Docker container, 4.1 or later is required)

**Comment by MaxGGx** [comment]
Having the same issue running directly from the repository

**Comment by LordNani** [comment]
I am also getting  ope: Invalid or unexpected token when trying to use /play command. Hosted on docker

**Comment by SpaceFahad** [comment]
bot was working fine until yesterday, it started having the same issue above, I tried rebuilding/restarting, but nothing worked.

**Comment by addict67** [comment]
As usual, it's caused by ytdl-core. Please take a look at this issue: https://github.com/fent/node-ytdl-core/issues/1251

**Comment by 60plus** [comment]
Same problem.
Fix mentioned here [https://github.com/fent/node-ytdl-core/issues/1251](https://github.com/fent/node-ytdl-core/issues/1251) unfortunately it did not work.

**Comment by MaxGGx** [comment]
As @addict67 mentioned on his comment, the issue was fixed for me after a downgrade for ytdl-core. Everything fine now. 🙌

**Comment by LiamTheLoser** [comment]
The fix worked for me after I ran the command to downgrade the doodad

**Comment by Rvby1** [comment]
> Same problem. Fix mentioned here [fent/node-ytdl-core#1251](https://github.com/fent/node-ytdl-core/issues/1251) unfortunately it did not work.
> 
> ![obraz](https://user-images.githubusercontent.com/73450566/266456104-acda050b-4e7a-4e72-9e3c-3c58569f591a.png)

I thought the solution wasn't working, but I just had to restart the image. Note that the output you see there doesn't indicate that it didn't work--it just indicates that there are vulnerabilities found.

In case anyone else struggles a bit to figure out how to apply the solution, what you'll need to do is:
1) Use `docker container ls` to list every docker container you have running
2) Find the ID of your muse container
3) Run `docker exec -it CONTAINER_ID bash` to enter into your muse image's bash
4) Run the command mentioned in the other issue to downgrade the ytdl-core library (should be `npm i ytdl-core@4.10.0`) 
5) Restart your docker container, and the issue should be fixed

**Comment by LordNani** [comment]
> > Same problem. Fix mentioned here [fent/node-ytdl-core#1251](https://github.com/fent/node-ytdl-core/issues/1251) unfortunately it did not work.
> > ![obraz](https://user-images.githubusercontent.com/73450566/266456104-acda050b-4e7a-4e72-9e3c-3c58569f591a.png)
> 
> I thought the solution wasn't working, but I just had to restart the image. Note that the output you see there doesn't indicate that it didn't work--it just indicates that there are vulnerabilities found.
> 
> In case anyone else struggles a bit to figure out how to apply the solution, what you'll need to do is:
> 
> 1. Use `docker container ls` to list every docker container you have running
> 2. Find the ID of your muse container
> 3. Run `docker exec -it CONTAINER_ID bash` to enter into your muse image's bash
> 4. Run the command mentioned in the other issue to downgrade the ytdl-core library (should be `npm i ytdl-core@4.10.0`)
> 5. Restart your docker container, and the issue should be fixed

Didn't work for me, unfortunately

**Comment by xHyperElectric** [comment]
I'm running Muse as a helm chart inside of TrueNAS scale and cannot get the mentioned fix to work. I cannot play any song, via Spotify or Youtube.

**Comment by nermish** [comment]
> > Same problem. Fix mentioned here [fent/node-ytdl-core#1251](https://github.com/fent/node-ytdl-core/issues/1251) unfortunately it did not work.
> > ![obraz](https://user-images.githubusercontent.com/73450566/266456104-acda050b-4e7a-4e72-9e3c-3c58569f591a.png)
> 
> I thought the solution wasn't working, but I just had to restart the image. Note that the output you see there doesn't indicate that it didn't work--it just indicates that there are vulnerabilities found.
> 
> In case anyone else struggles a bit to figure out how to apply the solution, what you'll need to do is:
> 
>     1. Use `docker container ls` to list every docker container you have running
> 
>     2. Find the ID of your muse container
> 
>     3. Run `docker exec -it CONTAINER_ID bash` to enter into your muse image's bash
> 
>     4. Run the command mentioned in the other issue to downgrade the ytdl-core library (should be `npm i ytdl-core@4.10.0`)
> 
>     5. Restart your docker container, and the issue should be fixed

this worked for me the second time I tried it, I'm not sure why.

**Comment by EricFROL** [comment]
Any definitive solution? I'm getting this error aswell.

**Comment by EugeneLeclerc** [comment]
You can modify you `docker-compose.yml` to something like this for a temporary fix:

```yml
services:   
  muse:     
    image: codetheweb/muse:2.4.2    
    restart: always    
    volumes:       
      - ./muse:/data     
    environment:       
      - DISCORD_TOKEN=redacted      
      - YOUTUBE_API_KEY=redacted     
      - SPOTIFY_CLIENT_ID=redacted      
      - SPOTIFY_CLIENT_SECRET=redacted     
      - DEBUG=* # If you need ALL the logs
    # Temporary fix for https://github.com/codetheweb/muse/issues/970
    entrypoint: bash   
    command: -c "npm install ytdl-core@4.10.0 && tini -- yarn start"
```

This makes it download "ytdl-core" in a bug-free version when you start the container, then start the application normally.

**Comment by Rotekoppen** [comment]
@xHyperElectric

> I'm running Muse as a helm chart inside of TrueNAS scale and cannot get the mentioned fix to work. I cannot play any song, via Spotify or Youtube.

![Settings of the "fix" in truenas scale](https://github.com/codetheweb/muse/assets/33429716/6ae15845-35ca-4413-8cbe-2ab6f08da636)

**Comment by EricFROL** [comment]
> You can modify you `docker-compose.yml` to something like this for a temporary fix:
> 
> ```yaml
> services:   
>   muse:     
>     image: codetheweb/muse:2.4.2    
>     restart: always    
>     volumes:       
>       - ./muse:/data     
>     environment:       
>       - DISCORD_TOKEN=redacted      
>       - YOUTUBE_API_KEY=redacted     
>       - SPOTIFY_CLIENT_ID=redacted      
>       - SPOTIFY_CLIENT_SECRET=redacted     
>       - DEBUG=* # If you need ALL the logs
>     # Temporary fix for https://github.com/codetheweb/muse/issues/970
>     entrypoint: bash   
>     command: -c "npm install ytdl-core@4.10.0 && tini -- yarn start"
> ```
> 
> This makes it download "ytdl-core" in a bug-free version when you start the container, then start the application normally.

Not working for me...

**Comment by EugeneLeclerc** [comment]
> 
> Not working for me... Getting:
> 
> ```
> npm ERR! code EINVAL
> npm ERR! syscall rename
> npm ERR! path /usr/app/node_modules/compress-brotli/LICENSE.md
> npm ERR! dest /usr/app/node_modules/.compress-brotli-MR2CqwiH/LICENSE.md
> npm ERR! errno -22
> npm ERR! EINVAL: invalid argument, rename '/usr/app/node_modules/compress-brotli/LICENSE.md' -> '/usr/app/node_modules/.compress-brotli-MR2CqwiH/LICENSE.md'
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2023-09-09T13_03_46_552Z-debug-0.log
> ```

Can you try with a `yarn upgrade` (or whatever the install command is for yarn) instead of `npm install`?

**Comment by EricFROL** [comment]
With yarn upgrade getting this:
```
yarn upgrade v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
error An unexpected error occurred: "EINVAL: invalid argument, rmdir '/usr/app/node_modules/.bin'".
info If you think this is a bug, please open a bug report with the information provided in "/usr/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/upgrade for documentation about this command.
```

**Comment by EugeneLeclerc** [comment]
Weird. Probably nothing to do with the current issue tho, I dont think we should troubleshoot this here.

**Comment by yardbro** [comment]
The above-mentioned workaround definitely works so long as you can get ytdl to downgrade before yarn starts. This is obviously going to depend on how you are running the application. For those of us madfolk out there running this in kubernetes you can fix this in your deployment or pod manifest using:

command: ["/bin/sh", "-c"]
args: ["npm install ytdl-core@4.10.0 && yarn start"]

**Comment by xHyperElectric** [comment]
> @xHyperElectric
> 
> > I'm running Muse as a helm chart inside of TrueNAS scale and cannot get the mentioned fix to work. I cannot play any song, via Spotify or Youtube.
> 
> ![Settings of the "fix" in truenas scale](https://user-images.githubusercontent.com/33429716/266773047-6ae15845-35ca-4413-8cbe-2ab6f08da636.png)

How do you do this with the [TrueChart's Muse app](https://truecharts.org/charts/stable/muse/)

**Comment by xHyperElectric** [comment]
For anyone trying to get this working with the TrueChart's Muse app:
![image](https://github.com/codetheweb/muse/assets/71343435/4a7cc484-a98f-4928-8453-ae144ba80116)

**Comment by EricFROL** [comment]
Not working for me with this new release. Not getting any log.

**Comment by EricFROL** [comment]
Any update?

**Comment by xHyperElectric** [comment]
> Any update?

If this is fixed, I'd like to know because I'm not updating until I know it's working.

**Comment by codetheweb** [comment]
v2.4.3 is working for me. If it's not working for you, please open a new issue following the template.
