### ISSUE TITLE
Add a /play-skip function

### ISSUE THREAD

**Issue by hennsoe** [codetheweb/muse#980]
Combine the `/play immediate:` with the `/skip` function for instantly playing a track.

Implementation suggestion:
Using the already existing infrastructure for `/play immediate` and instead of saying "Added to the front of the queue" it uses the `/skip` implementation. -> "`Aright **${firstSong.title}** comin' right up!`"

Shortcuts:
`/ps`
`/playskip`
`/play-now`

**Comment by codetheweb** [comment]
open to a PR for this
