### ISSUE TITLE
Spotify Sound doesn't work

### ISSUE THREAD

**Issue by Dreandor** [codetheweb/muse#984]
**What's happening?**
If I paste just a spotify url (no playlist) the bot is saying: ope: No video found.

**Logs**

```

```

**Screenshots**

**Additional context**

**Runtime**
I'm running Muse:
- [ x ] Directly from the cloned repository
- [ ] Inside a Docker container
- [ ] Something else (please elaborate)

**Versions**
- Muse: 2.4.4
- Docker (if applicable):
- OS: Debian 11
- Node.js: (if running outside the Docker container) 16.20.2
- ffmpeg: (if running outside the Docker container, 4.1 or later is required)

**Comment by codetheweb** [comment]
Muse does not stream directly from Spotify, it attempts to find similar track on YouTube from the track's title and artist. If it doesn't exist on YouTube, you'll get this error.

Happy to accept a PR to make the error message more clear.
