### ISSUE TITLE
Enhancement: Localization

### ISSUE THREAD

**Issue by Dan-Mizu** [codetheweb/muse#986]
I understand that one of the unique aspects of the Muse bot is that it is mid-western, but it would be a useful feature to move the end-user facing strings to a separate file that could be edited by the deployer or perhaps even a full on localization feature where the community could pitch in to localize the strings to different languages. That might be out of scope, so a simple file with the strings capable of being changed could suffice.

**Comment by codetheweb** [comment]
Duplicate of https://github.com/codetheweb/muse/issues/319
