### ISSUE TITLE
How to use favorites commands

### ISSUE THREAD

**Issue by rori56** [codetheweb/muse#992]
Hello,

Just asking here because I dont see any explanation for commands even if they are easy to understand.

How I use the /favorites command?

I assume its to create a playlist with search entries, so I tried, created one.

But how do you add entries to the "favorite"?

Thanks.

**Comment by codetheweb** [comment]
try `/favorites create`

if you start typing `/favorites`, you should see an autocomplete popover in Discord with additional help info for each command
